// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.32
// source: common/commonspace/spacesyncproto/protos/spacesync.proto

package spacesyncproto

import (
	bytes "bytes"
	context "context"
	errors "errors"
	jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto struct{}

func (drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	var buf bytes.Buffer
	err := new(jsonpb.Marshaler).Marshal(&buf, msg.(proto.Message))
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return jsonpb.Unmarshal(bytes.NewReader(buf), msg.(proto.Message))
}

type DRPCSpaceClient interface {
	DRPCConn() drpc.Conn

	HeadSync(ctx context.Context, in *HeadSyncRequest) (*HeadSyncResponse, error)
	Stream(ctx context.Context) (DRPCSpace_StreamClient, error)
}

type drpcSpaceClient struct {
	cc drpc.Conn
}

func NewDRPCSpaceClient(cc drpc.Conn) DRPCSpaceClient {
	return &drpcSpaceClient{cc}
}

func (c *drpcSpaceClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcSpaceClient) HeadSync(ctx context.Context, in *HeadSyncRequest) (*HeadSyncResponse, error) {
	out := new(HeadSyncResponse)
	err := c.cc.Invoke(ctx, "/anySpace.Space/HeadSync", drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcSpaceClient) Stream(ctx context.Context) (DRPCSpace_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, "/anySpace.Space/Stream", drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcSpace_StreamClient{stream}
	return x, nil
}

type DRPCSpace_StreamClient interface {
	drpc.Stream
	Send(*ObjectSyncMessage) error
	Recv() (*ObjectSyncMessage, error)
}

type drpcSpace_StreamClient struct {
	drpc.Stream
}

func (x *drpcSpace_StreamClient) Send(m *ObjectSyncMessage) error {
	return x.MsgSend(m, drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{})
}

func (x *drpcSpace_StreamClient) Recv() (*ObjectSyncMessage, error) {
	m := new(ObjectSyncMessage)
	if err := x.MsgRecv(m, drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcSpace_StreamClient) RecvMsg(m *ObjectSyncMessage) error {
	return x.MsgRecv(m, drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{})
}

type DRPCSpaceServer interface {
	HeadSync(context.Context, *HeadSyncRequest) (*HeadSyncResponse, error)
	Stream(DRPCSpace_StreamStream) error
}

type DRPCSpaceUnimplementedServer struct{}

func (s *DRPCSpaceUnimplementedServer) HeadSync(context.Context, *HeadSyncRequest) (*HeadSyncResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCSpaceUnimplementedServer) Stream(DRPCSpace_StreamStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCSpaceDescription struct{}

func (DRPCSpaceDescription) NumMethods() int { return 2 }

func (DRPCSpaceDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/anySpace.Space/HeadSync", drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCSpaceServer).
					HeadSync(
						ctx,
						in1.(*HeadSyncRequest),
					)
			}, DRPCSpaceServer.HeadSync, true
	case 1:
		return "/anySpace.Space/Stream", drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCSpaceServer).
					Stream(
						&drpcSpace_StreamStream{in1.(drpc.Stream)},
					)
			}, DRPCSpaceServer.Stream, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterSpace(mux drpc.Mux, impl DRPCSpaceServer) error {
	return mux.Register(impl, DRPCSpaceDescription{})
}

type DRPCSpace_HeadSyncStream interface {
	drpc.Stream
	SendAndClose(*HeadSyncResponse) error
}

type drpcSpace_HeadSyncStream struct {
	drpc.Stream
}

func (x *drpcSpace_HeadSyncStream) SendAndClose(m *HeadSyncResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCSpace_StreamStream interface {
	drpc.Stream
	Send(*ObjectSyncMessage) error
	Recv() (*ObjectSyncMessage, error)
}

type drpcSpace_StreamStream struct {
	drpc.Stream
}

func (x *drpcSpace_StreamStream) Send(m *ObjectSyncMessage) error {
	return x.MsgSend(m, drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{})
}

func (x *drpcSpace_StreamStream) Recv() (*ObjectSyncMessage, error) {
	m := new(ObjectSyncMessage)
	if err := x.MsgRecv(m, drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcSpace_StreamStream) RecvMsg(m *ObjectSyncMessage) error {
	return x.MsgRecv(m, drpcEncoding_File_common_commonspace_spacesyncproto_protos_spacesync_proto{})
}
