// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/any-sync/util/periodicsync (interfaces: PeriodicSync)
//
// Generated by this command:
//
//	mockgen -destination mock_periodicsync/mock_periodicsync.go github.com/anyproto/any-sync/util/periodicsync PeriodicSync
//

// Package mock_periodicsync is a generated GoMock package.
package mock_periodicsync

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPeriodicSync is a mock of PeriodicSync interface.
type MockPeriodicSync struct {
	ctrl     *gomock.Controller
	recorder *MockPeriodicSyncMockRecorder
	isgomock struct{}
}

// MockPeriodicSyncMockRecorder is the mock recorder for MockPeriodicSync.
type MockPeriodicSyncMockRecorder struct {
	mock *MockPeriodicSync
}

// NewMockPeriodicSync creates a new mock instance.
func NewMockPeriodicSync(ctrl *gomock.Controller) *MockPeriodicSync {
	mock := &MockPeriodicSync{ctrl: ctrl}
	mock.recorder = &MockPeriodicSyncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeriodicSync) EXPECT() *MockPeriodicSyncMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPeriodicSync) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockPeriodicSyncMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPeriodicSync)(nil).Close))
}

// Kick mocks base method.
func (m *MockPeriodicSync) Kick(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kick", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Kick indicates an expected call of Kick.
func (mr *MockPeriodicSyncMockRecorder) Kick(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kick", reflect.TypeOf((*MockPeriodicSync)(nil).Kick), ctx)
}

// Reset mocks base method.
func (m *MockPeriodicSync) Reset(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockPeriodicSyncMockRecorder) Reset(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockPeriodicSync)(nil).Reset), ctx)
}

// Run mocks base method.
func (m *MockPeriodicSync) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run.
func (mr *MockPeriodicSyncMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPeriodicSync)(nil).Run))
}
