grpcServer:
    listenAddrs:
        - 127.0.0.1:4531
    tls: false
account:
    peerId: 12D3KooWPdz2uVWaXGWj4JMEvThsc2oYYTwGSjv6wwb9CWjaXxFo
    peerKey: oTN6YSZGXx6afomh6gNx5js4z5TPkxvbSkFG1LW/GPXNWsfUfdvOOIQQ/rIoI3WVjmnr2gusRLD8e3wCb/Se1g==
    signingKey: oTN6YSZGXx6afomh6gNx5js4z5TPkxvbSkFG1LW/GPXNWsfUfdvOOIQQ/rIoI3WVjmnr2gusRLD8e3wCb/Se1g==
    encryptionKey: MIIEpAIBAAKCAQEAyJ30yhpI7q5YmaxsZ1TyWILsY3rD8LaFkJQMfC0GXq75QNmbPQvC94KAdiETsPHne7Rl8p6/Gp+4vdAzcYinG8EarnCpxAK4AgIUMBTn3tzIu1Yak9JNJUbznhzJTnfCI3CM6zM432iwbZVCMQ43HkIGcT3G25Hiv2QHWNnZvbKnlm6MUsC1E520e4jvhlwvgD2RF3+eXojThK2JIvm30b5KTbSjmgnpjd/2QTR4eFpF6MlQ6nOnA2GzJRPyAln9USCl9du2c4KaIoCp18e+AVN3EZk6DdRmzHlp0YqtrfECLYYYQgV4V3UXtBA/bx8pU7rY9vm6HZmxzET2hpS6kQIDAQABAoIBABOxNZMVC22qXXYQL7/g3b0EdPG63jrln6y2a5dQ0BxBLqRH9+4BFo03GSb/TjCDPkatSYiMPpP9c6PmKPaPBGA8D0NqOa/M2IUR8StbEfuVTnrdE9TIwtvS4Bz4FGaIaN0TsjFwILgFTbQj/5BTJePpdTpuZvOsmUZSKkp1b+Mn1r+/XnCPGRInvPcWR1I6EMv4oEIdhdWRhVGH/pfeLW+8uUCcOZ32tNuH5W5wZ8zBGjoPSqtcXwhuArY88yOemGnDBlQMKnWRwy0NZVAnQFLKTGnxrszMW5kgVtovKn5yiZNGR+kSDpcRder3bBzgsuIEJi3lnr34y5v3Vbb1r2UCgYEA4YaRvAuvD1k6eNL9NK+DNdbgOePvdYVku7jcvoufSN08go+SD3CRiHnbL0tDHwCW+cFJpzlB4ani0hMPEa7ufiaESQajFou7m7WsxPn+l9aFFLiC/q6L3RUVGKfTigBaF5QH2KEhGuSyW+l9QJgdaY8/VvyukXZK7So4rK3TzVcCgYEA47m97OSYXhZcbF/KjLJrf7BkN0vYv08J88ef6xvrPA+Z0RTKBrlGml+PGv53IU+dIo/wfe6EP/cfAgK2Japh00dJEaPKVULHe0TPqUWMUtrpy2+56wwQ7cfy8UbDzpKHHfE/FjpXlaIxrporkMuX3VitUrMb0T2XXtjtYW7sXlcCgYASeq5SVDrB7TPHVrJ8sKz1qmexFqY2YPnCEAG2c0ZX+BjPMehr73NdVW7KT0ZuseOtD1NzqlNlpD/7qqgfcNAF8i4AtdSDMmvq9FX1xe5AjslUy1GggLjhIqsZ3BaPRjwblnuWGo3V4EtlEJq8wjoWvjAYdpfvP1wgVsdSDuQ9/QKBgQDADp7Hc+OtNl6sZ/2Du9Y90p4ypJ0ge6CBIRMWTm2OMfogA9B+6zNIbt9afNIsHeEAjTTegJK4/8n/ABpumcv3TF+rqN+0GKX0qIwazrUSC96x3ICIY5zDbabPJkdtqNabwiLatEm5wRj1kMC9VXe3DlrfLH+BcNiA/aL2UX638QKBgQDYuGxqowg6Vguob2FAmaXQPR6iUJ0RG6IrZZXnEwrPdHvr63IGQzHV88ngG6zmG5etm1OIAbUVgHdcJ+5f+tipYu/2BweWXz26oA0ed4zSMAQvSN8KAjYojuI/2feddv2X67tF58Xla8gsK+AKhUEmEsuyXUXgtrXtx3ABI5vniQ==
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
stream:
    timeoutMilliseconds: 1000
    maxMsgSizeMb: 256
