grpcServer:
    server:
        listenAddrs:
            - 127.0.0.1:4532
    stream:
        timeoutMilliseconds: 1000
        maxMsgSizeMb: 256
account:
    peerId: 12D3KooWR5tEHzEqVjQas8PfhsGjWMooTWXsryDUz8HXWYnQhczf
    peerKey: ZeIGyAHh5/FOyPAFABPAGls2y8u5q9ndlXeWvWtlG9ni2QGe8+mu6KS6Lf2aXqDnALprDUSaeb/ezTAGB3NtDA==
    signingKey: ZeIGyAHh5/FOyPAFABPAGls2y8u5q9ndlXeWvWtlG9ni2QGe8+mu6KS6Lf2aXqDnALprDUSaeb/ezTAGB3NtDA==
    encryptionKey: MIIEogIBAAKCAQEArgUvy8MrSMDHzymuOC5xsPmQB93P+cd47FgeinZPS/DdEIXJDCc7VhbYDX4cZdxYgqoISJLgUN6/HNrAQILh1u2TA+meLPgtKCZgSgs8UGLYbQl1OoWd2BEpy7K6gxYNUu+mxvrMUOXSjU8Jl/yde8WeqZGBeNRQLHYXpw5DoSRQ91pag6Z8llIM/m11A8OUtFQMq1z8v4LHaQoi1Z7cyPJqLKEUS8etjJ8cHYWXF7b/68vbPmYiv4IwpWt7zefpfL5Qa/NcQgPm72HNz29P2V3h90Gs1muYy0Ka+GfCOcNqv4hnXfK78YZlACFBtBCn5Ar4CmT2LuXsIHe6qyXOqQIDAQABAoIBAF5LgTKwduvdSmf+9eCLih+Tm3AnyWJXrDalKSduJFnKEn+5fs+PEp/7kOb+xvSLCYsEB6kLrXEkwfoorrRGN4n3AgrEtGk5sX5oDRUSMYR9izjKPzOO45EI+9Tc7CPL9zxRj9WSYNQVNJpNka1BvTQsSWUo6zdGFIuDEh37pLnTxy2C3+uFaWI7aMUllU16ACO+0cNaOWKCKtASHk75SSTqnEh2P00oH5SBOUjmeAPc4eVpkzcR0+xbXQU+m0hs+9NKnrrQsNFUuWhv5Evvg5KrwWhEBcsbR4n8+q4YF2mj/eRbVK4eI7bc+vcrvF9MjuHpuuQPkQuH0ZqxDEuKmGECgYEA0kjm/FhaRlGgBZkh+z//Qch4dvK+ZtOiM8yKmYqctecl9mPL9fQoTMbTP7ml5y9Wt3z9msplD/b5FICfq327zGX+tFD3ZRXxtSzL0G0hTp6kh6Ywgj++pjK1tDV82uW1F8AHxsdyDl6wCmp0SIwF44j3kjpJ4oi9j3tMQX8doK8CgYEA09oI7SVvPYmTya8gCDBsZLM7kReEQPA8D8KVO24EdTYzjwpiwmQGocqxSmkQ36Rnn45/33JLnrSWMPVdXuHJ7XNvuKu94r3+2t7zUw4T/d5l7oBRXicEePz650IeeqoTddQgFEPIWXQmyo0XlKwZ48wbF0gLAev9l0c0iPDP7CcCgYBhREtjqdKH+DWWoVBwkReW7A2cp4eetIGwiAoMH2uBUFvk7iBnsfn6GXWZYlv05Zas5OnBcaDxk4F/FEfG4S++yebYrSLh5RaagQ/9Zp0jaoocHKkPdkDPS2F069DGx73OMIroTVTahL3U84y6CdqndrFdOAz49dsIxTVujke8DQKBgDGA12kiwDWu+ju8kk2XkxyMzTSAPEU4XbCJFXoHoT8KZU3dbWpjGTGhPYBXwLuhnR0pnTPHb2gsZpQWIbVUKW009jw+1WYwY2cdhdo4he9ikosCrQDFOURUSQTU7G5ZY6a65KwXkq9kdtQJ2CLDfGFAhmwQR5IxZNZ+qwX8z3ktAoGAPCU7XOZsRr6E+UIx17ghjNZ0Y/RwpmxqqOFuVPmpITO47BQIIQVL/gKqUOW649xfdpkTdIXc/eHeD8GEnksopO/O3Qaa8DkAHzQ+vVD0DAWzY1/2wVPARoGuo6qqNPEqRoKLy/TK5aZOO53rbVq+hiT90b6PytE4RWIATYqE2Bs=
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
