grpcServer:
    listenAddrs:
        - 127.0.0.1:4531
    tls: false
account:
    peerId: 12D3KooWSNzU7m619iEC6PVnRPUqzM5XtiFX3VZekyowTAzRW4yF
    peerKey: hEvfnX4IwcbH2Mqw1hI4q4xBHrlbZufPXBFq4ztz6hz2Fp7n1RsiG7MFgk6mqxLmXuB1drhlqfLZPCDYWRkoEg==
    signingKey: hEvfnX4IwcbH2Mqw1hI4q4xBHrlbZufPXBFq4ztz6hz2Fp7n1RsiG7MFgk6mqxLmXuB1drhlqfLZPCDYWRkoEg==
    encryptionKey: MIIEpQIBAAKCAQEA0nsJzf+y8waYqOu2jvH78q2typXTIKluz+RJ6CdRNH9CGwq2Ag7hwkYxxtr0Cq5EeI24+OAdHuJIeFQ+LLm1YE+RG+Hv/tP06kv3lk6b1jCaUVzu7y0Z+V/O4MclILMAF3gn+8K3+TFHdTfM8u3J3Hdbs2gA9y81Y/B+HXBpqnJ64E5fFFCTip+WUW+3HMyH+XC0c2JrCGdsuPQqdjIAO7HRb8us54kKP299BfKRe5FlAN4d8NliFGQVKnJiJP7RXH15Tlv3pUxMNefZFJCLFkU3oocHjs5/ykXC8PVTY7kkSpqa384ZN16ip+JWKcg+AqhWYDkiPy0mh5lFSZkO0wIDAQABAoIBAEzOXy6Pz1JFpvGFSlHxVbohzJhvgeKaUXiFWr7fkg9xHMNXbkFkAtfs238wKPu4yf2f4c7XoWjCtCVMwH97qQcjIdWl5fj8iZPx8sAjoVRQ2g80tXAL6j2Iy6pUoWTETRVDYHvLe2zwoZ3RpfVD9nSADbNzEV8iF/6HJM5DVhu/D1PQW7x/3jmI+GwnLDpDQ1UCv/xSiXqbqjZeL/+pU1L9NrSs2nPBsn1V4D6YCwRp84VgYLxaxl90wwDMhg1VBuakHLff7ZWl/BYiowCNZQQEvYRqWoeFopI7T8LjWoifIJxLWOL6ma3wgTkXPd4OQt319m5rWekUMZfUWH7bbyECgYEA6PGPuddpSC8faaP3jnKAEaBYZ6Jej6UB+PDsETB0YUruxbA/0/eSLo63mLJjgQ1BEZpuQmtj2x9qGQ6pkjwTcF9pEp1o7Hizemd1EClX6MLAATnKFlkqmCjlnVIAP5dgz0lfHMFaw1OEB7Re7UKwCYzTwuHx97lZ+Mq7ti1pOLECgYEA51BMhJ9hD9iqz7JCNuMPT7ZXdQWnky8wQ109DOOLTH2Nr9RGaojVtBVAdyU3NIWYuLcpR/Cub4WrOe6jOCGT87sCyctZxURjG1h55uO+xF+DGRZukxihC7IN982eC2qzlgqT9A76KdBDOCm6Hw8xSV0rObs19ddGYoWTtGRY4MMCgYEArdO85fhaJzSK42EpFdJZwU1/Su5+VADVRPg7oOQgpI2vOjQ4nSuMmVOEq9zKpf3HBaTRDJ1oqZZ6rPIlFevgsaVxGiP+rR+xBvF3CLVhVV8muoNuS1kEkQFLvyb26n1DD8v3vtSGr2V+C+XMRI7UIHxHdZD36F0XR7G5e8vNTjECgYEA5riAajRy4xRxY9NhGlAm4JJ274FhYXzK/hZNI8L/GZ+OKNhqGC8+QW6FK5JSWy/6YhxHr7sQsqo4XQN7iCxt38kkAdW0SABrfkYk6Tk2+bZvFCH8zvndAMZsCkTspGSclkccxm399qEFu0pbnElSFuQ4jk/+haVhTjoAVwlUYXMCgYEAyFjuNKLBDvOI3YNjKXmja8kDAi8xJSue4W2RmQoHuPXfH9VWec1cxsWMzOb20Y/9FhdhIXBumrFFaywIMh2CNEgEYpuE/cw89Nf6wMAt9p/hv1RtgwfWT2MV/VADm1teNvHjGweOS2ylvKfd01uGH63eWcmXrFP90RbGMl7zmv8=
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
