grpcServer:
    listenAddrs:
        - 127.0.0.1:4531
    tls: false
account:
    peerId: 12D3KooWSenwsYTswcHoC4JAZs7Yj18mzMb9VroQ5m4CK38BswEH
    peerKey: GSmkHGwLcP/9YwQoU41+mnFBN2meZzUWDpEgjHhZWMz6IuLk4tZ/UcEvuJfOZvYw/Y8tjLXJC3AwnEbqg6nA6g==
    signingKey: GSmkHGwLcP/9YwQoU41+mnFBN2meZzUWDpEgjHhZWMz6IuLk4tZ/UcEvuJfOZvYw/Y8tjLXJC3AwnEbqg6nA6g==
    encryptionKey: MIIEowIBAAKCAQEAsWJNZwYyoPdgnkq+pu99P9Q1f/O6vRGj1eWi4UUWJzhjJVZYi3kH0EvISE6m0bNUdKkcQnEqtBlGAwSYeSFTfCV4+6LKXQddm3nS3M1Y9O3uWvWND7R/cZ2PlIE5TCrvzFHZ6z3fR7oWoa+GcKseWvReWIhX5udN+oJJTc63Phhwq0JqY/wueBeNEjKfb1ydG+vvsMCl9BnwOUZyqhrmvQZin9dlhGaMKiPqN+NyrbWTDKCi9U7Tl/DaoEobnvjszUZgnESbl91Z2IGahu0wTimBdbhd6HbhScfKSeiYwyCGiPzXV7kCWL2rBwj3NKoTn0KjRuoWUV1PlD50NN5E2wIDAQABAoIBAAJqEBui3fWK6Gm/IrEq+U1xGflP2+7O2qgCpCDky9Rk1BSiBDqBvzV6kpNJXsPj6PZdhuDwoWAqJ+XKnjin13cNG4RxRsfVXdTL567RrLBIvMHILc9U6ZcmSdn/mEQNIY5qXsjw4qUbR0uUFARcj+E1CkOyN2ARLeKG+3Bvq9bQgIi4KFWCriJlxPpIE7mCFt9Y5pJdPZUMwdF3ga36Tniy2pKKqujisuOtKszxh5DlOXq87TLci58rG3wNRCHCuWXpCU5/6Uqd8mwV6p025ffOLqY8KyLv/zXt1PxP/U8TVjI9+IGYdRPAOxEDeIPOVXEoaBCtHbe+El611nfTAAECgYEA4Waq3hnlc6Dhfu59fCK89xYkqrut0yjz9csXfbOugvYGznp0+jSpT1vwGIl51ToyfvtdQqV9+XlSrBctrD6BfE3kzVomd7sq/S9yEVzTlPj4sf/E5CF0ZpTyn5TrxodnqjEdxevB0gQNhAx5JDPQggs5x6Jk0KESAOwK2wm7gAECgYEAyXbnmrwFnK8PNAIdB0r0fW5PVBeRHectMOUxf3FC7vf7MirEuqaGMvCgKp4+/lVwB3NMlAgj8SlQgW599fhUF+u9o3aTS1Dcif8P6LJGnNpQP9feaxw1haIqbdKOJk3nkB+SgzJKOXR0y+5alBJmaYt33Hrarw59NlMw9tN3xNsCgYEA4Qo4HneMdt1xReGmt4GXWLpq8WtgKSsCJ60VTxNOcMJiGVR55jUdtXX9SQI4+YKZV95vRlMkayeOOvMJTqc5cHn0rnILZg8g5JeyM1OSi3HoGw9Z7MraBHFBq8JrhFM8VNek+i5f3Obe96/cYyC4VJ4QmhiwvvuRlgoU7IvTAAECgYBBQyF3wJzYyuTT5jNdH2zgDRHpndDGrRK4miZUsG4MV4yqDay5AiTK76QS6jxhy2+FGlaeRZzPDKElrJNlUNJ9BULjZxAD/+fRVCzlJos1WItSgy1r6TF1Xrj75o9h3S68Q14E3g+pWQ5U2ZvCB8vhOOrVI38f4kOxi3V7H7nWrQKBgEDFFbqwOsIodAC7CiSfG12ski1XBv0+NzltL3npCWtQG2fWMhOjsBCp8tpjXpl7gREmvXe8qyfY28FrOvFvysbl5qqToXfTd9y7/Ji8PIiQCigCbTicrReMrnZcmpUmWhZ+25iaHUQGT6g1Na3EwKw1cN8p1YMekbJVPoAih8G3
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
