grpcServer:
    listenAddrs:
        - 127.0.0.1:4532
    tls: false
account:
    peerId: 12D3KooWMrYk1QLiE46aJBnLCfAawXJ6fVgppWp1DUNfXSiH5MxE
    peerKey: 7nBRbL4urB+itm7SJ40gjPYe/N5Irunyr6qkpKqlg1Cy21w4WpuKN/TSgaDoVqxvTbReLbu27hhxEzdTrLNO0w==
    signingKey: 7nBRbL4urB+itm7SJ40gjPYe/N5Irunyr6qkpKqlg1Cy21w4WpuKN/TSgaDoVqxvTbReLbu27hhxEzdTrLNO0w==
    encryptionKey: MIIEpQIBAAKCAQEAvBXWnAyZ/CGX4ROQjg4xrKd2CQw8uOHJjJaB66UDawAz5TLcL2WDfHHp7Mxua6+Fy/a62xp3OBwywyYGelGzNIWPd8oR5X1SUYzKqCR/p0ThybRKeUkYnj/UvjF1UzC8NUYNWBCjaZkO4HalYpjlbf0vVDryMWow4YE/0cb+rsxdxJx2t/ThKS808rz0WsKNcZObOM8Vt7RNkIfOKsdwP8GUKx7JMPa6bkobW7FvLkmCgHMPOo2uoAkQIMZLXSB9F9RKDCSBToW0a2r9Wilo99x1t9PZLzQbAKkuM4ZYkp63rfBzRRRPOJaAj9Cb0tan2nyQkRrVJ3yqGwyFjbe/qwIDAQABAoIBAQC7fElhZG5almH/SrFd6Wg64vMWMcyVvvxZ1+3KJ8MwdhNE9V3nIRngguzbzyyCy4RjvJ6mqcsNc45mWRE7/RTV1g0dK6CLUlEsWVvqH/fflRo9JirWm7aeiKJYtJRvSLVTpXDHyE4chSX/OkXB8wdAjJERNXEXMPNo1p33TpWxRu6x8mwAIBK+YFI+SjQNuAteOT+qKAKZsyLbv+kr0tBRyHfEVdYq6RHzbtMCJ2h2P6t1vywLGTPw9rUAYSFOnsYfl+RPAmmZDF4hH4teIJIWNlfESpppAFAIrIg5+RjKVM5Bm3Ez7vx3sXDPd+aabxKoqC3nakHcRwRYJD2Pc1cBAoGBAMYkxYj1C7FkJ16R9msptdiV+aILzGkpP7WLYSX6dtQbrwe8FK7UrCwfkm9Zbyr9HOik1SEem8ePgmZktCdzGyi7mci2BEvQTzDnN3T6aTG8808jP7X3Apgxw7ENhuNbxtygJdNZC3Szrvz7NS7bcD/SYsSJ7dNEn7StUZjGrf4zAoGBAPMBNOwvFQCALNPQFIY2tTStL6TlIJgcIfhUhF9pcwv6V9syOxepWe3v6d5aL0ooXU+59/V3pytNzc2SGeiKB0EuRye2Z7b79riBw+EqOMj6jG1DX8n8FfNhX++8mH7LMsxbcAN9jucIZHCUQm6WYedHwq6vvc5CYbCmsJ6z6VCpAoGABzhHylnDd09C7/s5k2YNrjqowfLUG/DY1XCitZOOyOPJWOrNhiFRtLnhyBTmLBbU+tUmvvIyku7zvW9l8RoMn0tWqy2WsnyApjOGnciSFLHh27xZEfRSL+GAU+8+PwKVGGztc+oGtNXnRmiQ44gzat/roWW1OMGDYD4AfySeKmkCgYEA4c62Qd7CUlPI1A6gc9M0cT2Zb03nCtHhkyPeWdbgLDo2F57GoIci5OIyXQdKuEtn4iT6UCQeuDO1URg5cQeKFDyPrExodfYO3obe4UXdvIxtnz6jLUtNjnpmrpx+zBvAGXvCS8wJ1Y/L3X03ehHN6h+Zvb/azWaL5p4Os3qVDPkCgYEAkwlmHO1BjozslDlY+GqhxOTWZ3lKR/B3C/QttmK9iBdRDc0A8Yj/TJteOgBkGxGKRz+1Z9JS+CTIY6/TVvib4NDLIZiomO+zIMrn4m5O77YnupIWwxoOf9MHPmQJaMQuPyxoon7eUL29rEmz0sYZMI8/QrACqPqTDyEcl4YJreQ=
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
