grpcServer:
    listenAddrs:
        - 127.0.0.1:4532
    tls: false
account:
    peerId: 12D3KooWS2ASPd6ThTBzez1j6qNPRETbNnKrjFg7EBnqKizEUnig
    peerKey: aFY5YOblyu6/2w5QsihT3U2J0ARiNzh0T5A9lVDnNlbwwLJ18vSkkGK4LKM6WjljUXCCPxcxYDqRTM0O/arkrQ==
    signingKey: aFY5YOblyu6/2w5QsihT3U2J0ARiNzh0T5A9lVDnNlbwwLJ18vSkkGK4LKM6WjljUXCCPxcxYDqRTM0O/arkrQ==
    encryptionKey: MIIEpAIBAAKCAQEAttySfcjFQgsqldabBebJQsKbb7FkwIwWtJwTdCVmGp4P/H2/kkZC+3rLqwXOYybX4D1eWkd4ZM7Dzi2Ra/h0RvQKD6wm6fRplLCZjZRLdYyuYO4oSWshSMceS/1K271NYTQtazkQYDMxpmhU+4PMtCj8VIszIbOY37Itfi+sy5Q/dp9gKh93LtloZJeqGuuLhyAXvHfJvhmBSk5g/Nzcb0JYePu0pHuT8QPVJGXfGgRuZpO7qqeTcx603tgOi/hlswxHLhdag4UELifcW0PiWWrJ3yrB9n+D1bzY4LgVr715pk8EKAq4JyQV6nuAENpk8oiyM1nuB8SGvWkJ7nITBwIDAQABAoIBAGsMiX21cTUOkGmTbsFvr9azUod6k/7cg9ZLoF/YHQPsEHPBscqR81iBNIX0KjSFYs9VXc0AFgz9tkcXChDpLDj1WIaAQ2+ms8Bl+h6V9+7i4prAETmZy6xtVOErcQ1ertP+1a/1gg6vKZu/bDCpoca+T6m2q8JI/2/FQTij9EZgj2WJxuJFvQy9HtWNN8UdIcp3av9h5pP+l8TY/Szqq7uv9X9QTi2aCC/t3RxolALTJ3zXV9Vu/dshKjSvC1nZ2KecfQgbb3sJskLzXBWJt2ThJMoblPw96G4zqwCmfY/QKpofpZ8tzE3Pk3ecZ4t1rPGDqvH3+Ma6HS4qwPWo+7ECgYEA5NSGd/ukAl27o6IW8yEw2E9/JmBfccWtn1YYJjQnnUTeQTR2JVukEPJPh67dTrKw1AGdIK7861YpMUs/r86azwn0PQezHKzhVd4vxbwFmgQA1U1QDY5CJmCpWGddZRgkS1gWZlX7b2+01+2/AWZuYuvccaPF54hlBVJIDp6V4WUCgYEAzJLLwX5gIUXmB1xmEaq7vCXbtIAiZI4564NHtiyEc9mPvCbev6y3LYT/B0nbWsYArJxM0uu2suHAzhjMUpAeFsOko81SqzLi9HaowgVqQw7vP7ilbHAe6C3uulmOX8kH1gnur6F8uydf3CjNh2GJMOm5II/FtFOpaV5fDkk28fsCgYEA2TlakSmjbs+WIWbsjE60tJL6q+6OjE1QXVJ4SEP4WxYWOiXYBeyxmZi8oJwB4ARHUmpZw735wFmhbvb09SqW0PWtEgZuJEmE+2OZTAcJ9kPYmqPy23txFkdqWs583UwGoDN1yB3VOtr6/IPnbyfSoDswn/wNEZbr9xo95wrqUvUCgYEAplQwcHk05bi0R4Xbwz+C9n39fWu1CvcMpq0NkFPvuVXJ5NvhvgxKvyrkQ+PMAqj8gVtvpwpZeGXO4oMNFY/xtuaJJVlafrGYD9WubloCxNUOt0uEzH740iQOdts7xCtqQJ/AvnHZPT3NVe6i9RDbf7Z4e74JrA1dr7s4JCBpGSMCgYAP7tR3uZ7Zv/5e5NqDqWoqx8zlWVSNCPIavzpTomTUHZ04QliFQqxHfR2HVvMVfCpfTzoH7Tms4DlPBkWw7QiZeNIrxK6iNbrnlbvELlJPosVNEtjMMB5J94kU9Ej7zQI2kWNwvGrse4EuY6lGZmN3OY/pSTcgbUdlBkCWASSDxg==
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
