grpcServer:
    listenAddrs:
        - 127.0.0.1:4531
    tls: false
account:
    peerId: 12D3KooWB79zLr5KqDCe3uHkEEZ4EchbdRNMMeZFrcVXeRzpBa8d
    peerKey: abZsspXm7Y0Ndl+oADxJskTS76KVvHQ5hBwZI0vOyAkTKMoaL+SMOISDiyPEFDoBQO9xwSXwTF2ES7dultLT/g==
    signingKey: abZsspXm7Y0Ndl+oADxJskTS76KVvHQ5hBwZI0vOyAkTKMoaL+SMOISDiyPEFDoBQO9xwSXwTF2ES7dultLT/g==
    encryptionKey: MIIEpAIBAAKCAQEA4we17FV9hPMq6jayCoLnWQri1tvZiCtroC5aRnzmosjxM3dBp7rjskQBSC8U89WWTRlQOMDxcCiq7meFiIoLO7nKL6YVw3w5w3hmc1s+/KIXkzMq25VC9OwrUBLR1rL7CR9slwYEYCizl+jS80q+unDqFeKPr9fqY8V6WSOrRRWqQtGLL/6Wq5KrgNc9rKwcIpvtb0w+UHewreVx2UBiasN/seydT0JEihIO0yyPxHtQ9ZtT/QV6IvRG4VE1UmxDAIIPc2gOJN9poiUCDlPDkogU2ZZ6XPUZ/nJwvp1Yh3hS5HjEb/5EiGSGgIQ1+tiKKREE/ZYtj8x8iJI+pnTT8QIDAQABAoIBADccdxAQzLCKav+CGYQttMVLvDcWFV9V0wGGXwm/ZilcCBlLONfjqURr97ezHi32yk6a93tfcvycEqpe3O6BPCradfdNJPlYXZlSz+Pu4YJoQrrL7/pv6FoWPolomCG7Pu8+/phGsKc7GiWlMhg3K8eMg3aekezIyDBCDuo2m2vgWkBzXrFm3s01doDlSkwMwvEx9UQpnekzUEC8qxjyfe9c5mEiN894/qsiiwCXIDwg0av/tu9Xrnz3LyejDoroSUnAKkSNJZJKXdUqxOGHlZSHqibS1H6WNouoQMdIyToQGYThBRBHpU7WynOXQF2jtaX4UUgAxMdUxEPCkmOjm/UCgYEA46Lc2CD/uI4hWT92PKHrZ54Js/V+YbLX7KziYPKQIkuvWIJjK4J6MaU+B7xc/3Thf3FWWv1+gTh3+9Li7swWNb8QEQhG6thz/AJgOSpeq3tvexIohjDhATsTAcnl/LEJ4jN93AJ+pOtqj+bCTFvBKn+w5dMlqaowD1T1G918Rf8CgYEA/1GECle4Xg6y1aMKq4KV2oK45q7X+28Vc6Rf1hfCFO8g7xLy4IfZPb5Ve1UEv76hqICYJpnBKXhB0I3z4Wf9g1nI0shnwve3AhNsw2oe+oMdUhVcbM249+Ppv8ZlUOG470BhCq6Hbzv5owPepxnR80IZw/xu3H7HBv7y6tj3Rg8CgYEA2ESK/OudCIJAPMKGWuSa+j6ziT3bbIa1ji5ShTjupyaw2K5H+bZk0XXkkQTsdeddte6/1IKyBaLYm2+oGqfbEgUMBqKOfeBXkT3QnX8bomALcim2Rod5vemaDUD8OC8a7MVu9e+I0ra27zCVuGYUB4R5VGBej+sY7fgRRwAOaZECgYAoRVI/U2C4LTdV7RaEwN8kDRRfBlr4xKesitO28B5jsOgP7XwzoBnK3FedUWajW80hx8633+6QvPAclhdOiVl6O1IqtQNwxCOwhyHTnMxwFPgt90KRws0XBHLdFczrOf8ydYQY7DheeiZA6R5YWwE7jkSEHi/aRYDdAJ+OHVS7TwKBgQCE6pWmO0g7PD2d4r9NPC6x6rp7KL6NjfYqia1VZJn2yJWikyMDQg0hNj1gTlC4dDpX6RhpFvNThHUPlnl2FHwpRkBe6/+Jv0sMdpB9Bj9nSKNrqOvWrfcIOqjU3D+W5nVM0/YWJAzb4xlC3h5IodEigOJaN+r9Eg8te34nb6lJsw==
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
stream:
    timeoutMilliseconds: 1000
    maxMsgSizeMb: 256
