grpcServer:
    server:
        listenAddrs:
            - 127.0.0.1:4531
    stream:
        timeoutMilliseconds: 1000
        maxMsgSizeMb: 256
account:
    peerId: 12D3KooWNQZjL4H82u9qdjpWFBFjFdZyTqvgXT6dajkJuRn9yE8H
    peerKey: SWdUoOefb/9zMLAYBgoNunIq4tzXm5Lr9Czn/Hs2IEO7DxBIWh7yjXSXpI5maURS7clClZOBe5PVO+1HCPKR2g==
    signingKey: SWdUoOefb/9zMLAYBgoNunIq4tzXm5Lr9Czn/Hs2IEO7DxBIWh7yjXSXpI5maURS7clClZOBe5PVO+1HCPKR2g==
    encryptionKey: MIIEpAIBAAKCAQEAsQGYl8hNwYzrug/FZ/K37dzUGxf6a2/tpMCVNTDwW5+UfGsWg4m1yuQwn3LubKIO9imC+jVLZ2XYisdu6WttFmdMzYUxflza5/xkuUjGuLkptKZeL996rP2xioKfMWaWjo8OpJ/jVr9HWx4buFWLqI01gwarXi5DnGKEg7BdvzcAeJO3k9VhhMTR5o5nCHRHaHH+EbOKV7rG+unDQYmoz1WgogJMbzNFTkOL8jxKpnGg36QDOtEQhngSyA/2f+nhucEihX5s7IfC5qw0cFHPovDxn0MSGAPYDxTsgZ/A9jz5agFDQ2PrTHJN0YWXg8IEvZ02A2kDVWos0pEGlE/OxQIDAQABAoIBAGPfVKv/lu/ohXEcSPQX3XPWr88Bvog0RVA6YXX7wQLRjcSN38wkPXDXRCAThzfAUNTQI1juDTewHXhggtItjQWhD5K+3mhAGDvhCywIRiggQcnuPSKh4+QL2MsgXJZRHg4d5dM5a9qcXrSozlc53W0jD9h4QOUJEZkBdWegcaTbgOovYwmMvsCEOQ8pDObd/uqWx/iid98//VtzEEDPw8/gC5hqMoJiQb1WPJ8y3Vrh94hinde6SHiwb7po36geMcsQ0kaWv3fAimyWW9YZSBgvBTnwRPXJXsnoIbYYkEH5GOV1d4l59RzMqDIzCuQGiDVmwQ1qhQ7Cz7lVHFlJcsECgYEAxIfCQUovW0Zyn6Fro9h6tvMccwWKRMLYkQPyOCMZNKwpbE4PxxvENJfr1jdQ/lljZbot1kmzqilfKOOCH4DCtwoRvZ985h/3wbw3IIOIiWeSoHq0dxm4kN6dXu2F3VyyVjz5XgJ1IL60hG6+XA0vkQ8ILDOac3MsvgrcKzBiz+kCgYEA5pFnIS7pzH8gtqSMXbI/Dyjg1KvNqaYqG/c2mbo1Gubm1tmTxAfe24vSTaOpSj1b3PL2xrpPrG6QlRRqb1ob3nR2E3I0RaLRCc/UUm/RVNfc41Kuisd5pQPq9nJ0CdM3A9TbRs54hyHFc1ObtN85hFbYyLTS6Avx+21wKzlZun0CgYEAsN4MsH13CQnpdkfre1UDe0pnPAysVx2TkU6f2m2b7Y9S6CmIgYQ3m61tjSfTOFRx48ceIU/K5US+Yyn8nSVgFyJ0vNafrOrwKeadJiG56w7PIqXLa7Q2KgpuTlQsuP8HcB0HvtcvWfzGsLiJkIY9XKrOjBkU0vnANnfHlQbCpqECgYEAkDnWHAC/iQbgzL8Dery8C1yTvxS08nEZmCK8yc6b13cmYLD7aL1Pn1/ILn64r9LP+tcUnN0AZ6lF0atSpNLl6fJJxgJDRmgBgLS7aNG/TOY2qxAWVINQyXM47+5KPbcci84DWDhhVo4+d9SN6sdTsD+vHWVXJIYMWS1s4+zc/vUCgYAkTPNny+Anx6/WS2bQ2rRz/w+K6CWA4JPxaZW04eX5RrBd6PbAyI6xmU8YfbcM4OegZUzGybmqCxkIGN8vgiI3h85ZZxt7foRG89DJAJbdCItandjps2MHM7NHm+qbgEYF69/7c5d6J2B0Z0wMzVsdk0eTrwnhU76CA4MjPabBaA==
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
