grpcServer:
    listenAddrs:
        - 127.0.0.1:4531
    tls: false
account:
    peerId: 12D3KooWE5UhTEvzfZhjDpbwademWbGHYzK6tfTVNrcAYNtZy5Gx
    peerKey: sKEX26/7hp9h/u0XQAdBWBeDBl7WLxP0fYMYOlw7pho/Tde8/bFwSjZfHw9X3l//NaFgnbF3iH19y3vDSCUNjQ==
    signingKey: sKEX26/7hp9h/u0XQAdBWBeDBl7WLxP0fYMYOlw7pho/Tde8/bFwSjZfHw9X3l//NaFgnbF3iH19y3vDSCUNjQ==
    encryptionKey: MIIEpAIBAAKCAQEAyVHYPs+5RWYn9eRYkcR2+kciJ1tO7TUVHm+R3EXKL0/70wjtEgylA1cF5KwjRphkQhLjKGTw3wgXPlHe8KNT42c3/eRrFEikrOhp2OHqfEa0o3KGZTXb4AoRM0DDcWHL2K3A3fvmlHYOGtTzsJUp0NIhBQn0GzWcgJkE4CG6NHbZh3WADeYj8s8qzKeXw9LSzqzkjRix1kushLI9bIaziH4J3ex1L/E03aTHARiWTgLQesrkXl1VixrlYpePgvSeK1H8XJXqZQ9CXSOOO/0kcY00Qc+0djgHvhue4xvcYT2wgYBW/OLZvCpUBwt10JYSB/UShuW6udp+GodviWj2KQIDAQABAoIBAEIzjsfA6SzgFf3vFA0DLRjKMXn9taudTA+RIsbrkDwUsjvIcKUB0XWStVZoIMWDMVzk9xv+bZL6ByKwK364Rsq905TC+09VQAm3966hQ8mQOrCQ5Y78sgwvY06WWm67eRwMryKQRlfFpoe+RVBpDLIll0Qf7MzRyWAkcYz+qku7v9oqhZtp/nuSOuaDsCfK37pck+Ms03+sL/O0RFZq7eBosGnxBwCvuaigBQT/dPSiD3xKGrmwPDMCDfYiCIBcyQIJrULf8Dk+07N82fXJP2aZyJTCW8voFgQ+ZviIqcneh7dxLuKySgYqeGrO32FOKKIorQ0etuM+UvuEBW3CT20CgYEA8fovVzTD/fpnJag1G74RHs4rLBXVhtytcp6nTYF0PdoFJehzWl0V/lEoZvzsdV9REzKWhjpgPmrmDK+E7XgbyTCIWLDLPQfddJ0ZcTAecaouihkmvTWMdWZATPeQKatcwtlMc0/8sH8oSC+Near9ajr87Kb+Sva9afok8RLt2n8CgYEA1Px9peu6e7d35X0IRKZScKuOy9HCKwE5Z0PY1PgQePG2HaukHlrlQil940zyuA2sjAQ6IPecIwyaeFANGg+heOvJ2X/NWUihufTSg+7V7fj/SaMbfp7Jjf3bo1+wZlXYvKU783/XOItwFaNymlKlbQhP5/DkvXApUq6iIR8vy1cCgYEAsfcXKkQcgYbQpdl4ddbsMIPhLKNCT9Wtm0ckNNSo8XSPpLm5XRRpQInf9R6/qfNYZY4nNsFoV3+3gkz0rtJPXUDchp5AW7qVHVcNhzmkqmRHpjmpTC8+BnoVgIXy+TKXHpdCquyBJC3hKnYOzxT7HE4WBtcq32dpF7BpywPo+3ECgYEAqAPCTshFZOEXaOaYRid6cz0yuWBwLqKZmPexrlc+D1qGEqPbJMMJhYbbsxp5gm3vBsky3dzWw+NmW7CylTNtasl+guBJqrwcMGiMRN18z2yUXo+X2ewDDcsLn7aVnjTsc+xY/b6EliuRMNCuUEUQEJH1DwA+QZ6gSoROi5hhiKMCgYBv7shoLVGd+YGADjDoBUszSAL+9OfFB5xQIIUeNTWJnyLBFDgOXCE8Pyo8UO1CmKMoY1CT3n0xdCoRX9EFBrsHjQDLOMePN27IexkPdjm6iMX94QNWHYg0X9hD2zcNkF0v4mRmIAafZmPOWbVzVdmNhNFN3Vfkss+jMNtNOaCiIg==
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
stream:
    timeoutMilliseconds: 1000
    maxMsgSizeMb: 256
