grpcServer:
    listenAddrs:
        - 127.0.0.1:4532
    tls: false
account:
    peerId: 12D3KooWMh5Z7eSbgdFFuz81dWKnBeCP1S1frQU4S5SeD9KuWUCM
    peerKey: 4wipbFiimbNv0Gdt2II4P31dUK60TDjuzsEyITzEyH6wbmRAlopFOMVcyVN/Y/1mFw2zmn6BQjwqGFJHpunPZg==
    signingKey: 4wipbFiimbNv0Gdt2II4P31dUK60TDjuzsEyITzEyH6wbmRAlopFOMVcyVN/Y/1mFw2zmn6BQjwqGFJHpunPZg==
    encryptionKey: MIIEpAIBAAKCAQEAuQRTl+54K1K+V/NVeWLBMikc8Jg1BfbvY3Hj8HR3VSnz/rhd74kln73SOTLM5Lqda83X7Ev+oBM7iN0R/IOliVFyEVtZLQBzpK6U+Y6KWjIgGWXBSYC3xvIhRfLnRvuxRgPHK23hmJQB8rIE5uGhh/1yqQX0+tuiEgbJwC8XoX6DP5dfs8DMcniTm/kX9de1KNp6UndoDLQN8Dg3PMv4ydRD8wxC+MHNg1bwdbtInzXB6AZZqwfBjBTIGMKeyokQcY1fgTQxtm55MWPxtLKxEaugLvTkrRAZtuyvnrMSPCC4D9S+RpEhEgS3s4KQ3Us85yfQ+Q9MgePduXTX7jUfAQIDAQABAoIBAH+snacFmAWFdvaoY759SIa92kupLUXtbqr4R+yB4mtxpP+M6L3IrZ77VdvE06Gvqbxf8vYMRyzduMKsk6HmktAc1RNnLzWfzy3Aj+ta0tyFJKOCFY0Md0WhhxaHFdRlEaMYLlQo4nnxARsif8F3yIlYe8xp4PFPqRq5dnXZyXvV7h+qofEWkn92MEArXLsX/w2DH9lru8Pw1CxDrk17C4/hTKJv7JeGH1a3QjLE+5odqw/zCrAxob60pnxVQrsq5uTeq3eSfWn4i2frZ3oTtoYcD4X0HmZTPqRT/FzrsyasDai7/pPC4AmS17yObtOaR0+0oDTEABKpPuCshD3XQPUCgYEA5YCxVD7fU387AWHe+OEfjWFoBgcKasrUA/zF+0VhY7rVdzG3WK6yqWTO0axQ0N3jQyvtQjoBUSwtjnFgQIIkwLjMJOB3A5nKb3T7SCC35Va0ZkZPQVaTcMgEZ6Y7s6rsSYTxSPkBde38AQOukHD0Y5vB/ZVcqwS2OrPAZVPoZ9sCgYEAzmDJfradPfpdAY063OC3k8Huw6z0T2lH4bWWkm5WbipE0A0YcWeqZoHtoFoN3Tns11vrHNiVcVRQUwCF3wH7XSIG9bnSP7gnf1IZM9ixRF6nvgnAjVgNISqfe2odD1y3/NQGdiXVKLT9skTxqTRml2Thz1+2KIS9L6vbmjgaSVMCgYEAqKdvKUre0Txhfz2OHvVJO5uGV0+bPyl4rsl2MJYm4KQvNN2rMBeJoeQ7/GeWKDe3R+ii/ZUk3KMLg28b3awGGD51fvAZZeMBmfCsrK+mlHmoLrSij5Bw32ONoSHPI9SKuehhbE/Y2/IczB4JjYoEfqK654B4zhCzXeY0kAIeexsCgYEAt3mkqVqAgNFMTkzYv/WoP1xygNQKf28B0NA3hQdDH73EX5LE4E1hWLC6KYzmNn+A6BV3+LU0ZwSmRKR6X8DLUAkoVt1U5gE6XB8I+Ob08euVBYZ2ATL+uTXDg1zbaQTtLYDyHaeU0hPWV96jWeKUMpQljM9yiqM37mHDYl/uPrECgYAPgKiax3krqQuyM2Fb9ObKWTsqsKdfmQFr+hm3x4N1rU2zvwKIRTCuVHgGhHMLZh3W6aht2cYmMjTTUxP3c8kk1VyJ0FTqlwxxYoc/gkSmO7Nd5fUtSunEsJ857xVTHWrp4PzXM7zpghV3tGLETbz7eF7XgfPsxN3J5UAiUrE0Og==
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
