grpcServer:
    listenAddrs:
        - 127.0.0.1:4532
    tls: false
account:
    peerId: 12D3KooWRRryc9JSd5qdRATTLCB21m9ELopJvbTiDehyovQZvgf3
    peerKey: Bn1itxyTCgOmB7Sk3CgZ20KCWMNvux90oDl9T/gtnKTn9zSa61s/Uoqww3egTYtgkBuy60XEIL1i4mHGzxqBAg==
    signingKey: Bn1itxyTCgOmB7Sk3CgZ20KCWMNvux90oDl9T/gtnKTn9zSa61s/Uoqww3egTYtgkBuy60XEIL1i4mHGzxqBAg==
    encryptionKey: MIIEowIBAAKCAQEAsK4Lqo5KzWVUmoHIud02xBL9hYIPiCVFlYgwtzA1I2gJEC2wLmycbq/2PRInNNYPl0sDiBvRVlQKTGzPhGyDQMD1lBuP9Jv8H345ThLQ+EuRtLqr2LQOVn98jq9MV7/sn9uGGW1bp1nkHXw9ey/XbRy7BhMrIoIf6oFgJFq7aoBybSUdTNtC+aQtoitf+GXTWCY3KRnwcRfHeNj80s5q9/6Ru2SPHcCyCTe2MgZIVHG1RFIF2PqqcXK/jziz6z8ekByTi9PpOd95newd0WwXO8fZVPpILJ6Ii3VGiHldtoGcMMipp4slWxE3sv44n9cvy7zwnDCINtBwLlYYR6c71wIDAQABAoIBAHYgF4qz0g1bh2I6DaM+5MPZUol1uL609L4SLUf9Qjnm79BSS63uTfSvTvnr7iykRg5ISBczShXm4G/SfDg0eNjNaiPY/bl0pO/Fa7joWbD4jXWBLS4YzFFGsVeQmoE8v47trc3IUPQl5J9WFqELDoRUJjLclAVhbMdUMpx70TxVgYbmELjtUwsjWnBuHQv7YbAbN2QFmdUFfZOUpQZno8ArufQtB+B3rZVzemHjb5+fB2PPv63LHJKhDoZ0HJvSWivBQYGmL/Aph10sSkqfDk+6F64RLGs+uonWcL2SK485aUZLQYweRCo7u+409QD437ERzff2c0Wmfu0t+hlRzbECgYEA5MqWg7Rp1Z95NHTajsOm95ea65EB0is/wqRa++fng6FQ3UsGF9aNjo2R6Io/BUYnvqkTIbD26pqDCSVBOiuRk8fnw66Q4REP8ceKlvk7gwYByUFTPz28R0YeJpbt2P7lbEmm5HuyJ5sMbCW9TzDhatoDA+f1hNMj8UhORBfMPb8CgYEAxbD0jbHDnQ8o5tg1/FoqBGy0f9kOixReKKNhBvVbKwrYn3uHOoZsgXDnKgXa5UEjWC1CmS00OOi0nW2yQmRBRm+jO7wOEnslYf9WuiRZrmK5LwAFyREIQXdYo/RPGz2YjNjGGkPMCukHFxtp2VB/gH56/TvX/9SoNbSyffBBN+kCgYAVWeKZ/+gwi2VgQ9dxo0idqoRGn42v82FL5NKo14d/fTpyrGGxL9CeERAgx2YCM/3ZiSXD6yPf2POJkvR3XUGErQ8v78aNem4mfhys4i1vmMvp4DLIoBZGAIEn0MX5jjAS3vy4LeL+VzXdkdgM397pfdbyMl9zOdEM31aOfDoPOQKBgQCQj9oFU5yr2U4boLe5lWVsXuGPK/aKlZZVOUPWhszoKMJHvVkh3vKxpRIllKqBQqTJ8i7lPD0X8HNDO9hC3HUvQKupHtdbhFnN055j9/jsoJyyVd3lLmNPHCrhmeHPFbfcJxiWVEV9JPJeX1mD5G2YVOUzEPPezG9E9qIfnfTTIQKBgCst1oRJ41uiJQ5Wi/v4O6niIZGptpNxXgTWeBiGl11d0bFujYlTx25jpQGWvF6ZZWbhUtNR9Kjpp6QGqNxxcWpQehKFFPytEYkkbA3roUC/k5E7CjN3UfWNte5kJ/pnlTZCE3+6VOwQ9Cdnqh4mPxIdRxv1Dk10xLpd4iGncbRU
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
stream:
    timeoutMilliseconds: 1000
    maxMsgSizeMb: 256
