grpcServer:
    listenAddrs:
        - 127.0.0.1:4532
    tls: false
account:
    peerId: 12D3KooWHKcJRGnk5wHYo9Tgy5Dg48pX3D64mQU6yjkWcmzK1R7P
    peerKey: VhENG7mg6uNVoor852BDJD68zZpY/2ROX27m6qSf585vf6GkpR/lCL77GSN70ifDEgstGF1f4c3AoVMNYDqOEg==
    signingKey: VhENG7mg6uNVoor852BDJD68zZpY/2ROX27m6qSf585vf6GkpR/lCL77GSN70ifDEgstGF1f4c3AoVMNYDqOEg==
    encryptionKey: MIIEowIBAAKCAQEAmHu87SqfW1dypmaBGqbwSraRI3DPV3cGObbbf953+AEtbTszx2c6tVJNX+3lpC1D9mZm9iY8MRZjoeUFdOjx0bzE7CIDKgtWixE4tJoEqzpr8UeYKsUYtJeWpANSJGeUUoeBcY1aQKkxJqGTXLxU3faOfxfUyKwlJ1If28pkSeaEPxWtdcgEx7ddKCic0Z7FkjVmqqpoSaSMf7rKByPJL3zHb21FohNQKAyVLoMno7IK6p8oW1TifOcS2f+Bt8nAxt27XJKbCwOoXazsJbm5HXjMNxg4l3riR8BhA38rTvhfb4gblIcF79Lx8W8wvjtoBcBrAcG+HWRc+wXCgim6PwIDAQABAoIBAByx5HrJM5Xv3e58ib0nPz8AHk4KE6rFBlHkHGhyyCbOqerNYlAbGAw5QcBUt4tuzURYPvYBegBO008LFzzJ/X/Xw0Mgn3HREmc3RXGPLmO+qcONEpCx6JVLlZil21Zoe5wQTga9cAeND2fSrjWcZ2gh1u0J4gwlgRRmOwKUkszpHwbjmgs2KwvrCFF145ol7N6z+xnXRKwykXqe5Z1pCfOyy+qY39JWT4DsepjAOpw+g3Z8JXgSp6tauGgcJbGh+lgFtr0g/f1WQw7VxZO+hdCPY1njaxp9i98uz3DJlUddKdoXQBOzr+gVB3wC7I7woNL6ELS36wwmX/wa7lk4TPkCgYEAyeNKiMIu053ON+EKq3deDuNV1p2ER13sfU+bvUPEq0bQCsLQFz6OAR0qOHabvTmYdnvJipE2/xP1/GXX5lbO2mvEgg7adDDWwhOjaT3voeQyj1ezP3r5nvfH6dC04RGegJflLHAzOfcfrjNASbCvJHlQEtOJeJbLhBedp/sIxysCgYEAwVqDqBQYQ1MXc0YIhRo0nJlPPbtGQBFeJTUjAnYOx0tG+MzQHGiVMQB25AfSwTDj4v/aaYnuu6jTHn2GiMOa2zA7xNu5ygTI8eP6GdI4ch5JH/kDhIT2iMWhMFytj3y2xpeuWOFzwBpkBa18YLbh2ebsGy3lP0bCcSy+dyTUTz0CgYAh7DMl75r2q9luwj2Mui3vynst6KHFbB7En4/HqY9uSCPE6x8UCMrLnR7vBd79WKQppHsk8WmQSsZWdrZkWcnAIcOPJvfF9j7ftXULxgBx72ofc9kGnZ87+t54hz0dZFyBtwQnB2NUJhYIq0vuFeYX9tphj3HV9WCU/XLcOu4qqQKBgEeDIbSVkg+8eKzi1x3bfl/49+zeCfKCOe7LA2LSpU6ikeJNZh9LsvpHsLFQD2vymCaJ+I8WO9zeaQ8a4BpPNkQhR8ncdo+4S1Xjusm4DbZvax5PLDTkNIaLib1oWaz7NGKpEQvAft4rJJlQ+/KNUWUVWngG9oX7tsjDAsLwNTIFAoGBAKBhYmGsNn/E6PQGW/I9u1QrAwtB+HyYG4i6aazyonlIfKRaBd4RMTN4twhSilTIZb/1DOyq/yWfANsci03gaH3sv14E4kb0hFyTlDmu+XYJGSh4AKZLVU2fLbZIkSDrWogL8+VZaQy8tdwQAJ3yUpHw5+Aqxv/HE1tinyI+FSqk
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
stream:
    timeoutMilliseconds: 1000
    maxMsgSizeMb: 256
