grpcServer:
    listenAddrs:
        - 127.0.0.1:4532
    tls: false
account:
    peerId: 12D3KooWFGB9ujKw8kCZB1hxx23uT1XmXftuJKCDKjS4mc8s4DWU
    peerKey: C5mG044YYpB7dckuIXWLfASCnhP6HyZTj7EsDaE/Or1Q5xTnpKWjMfOcRczHEDgvY2o0o76uCjf1W+m4D7uFFQ==
    signingKey: C5mG044YYpB7dckuIXWLfASCnhP6HyZTj7EsDaE/Or1Q5xTnpKWjMfOcRczHEDgvY2o0o76uCjf1W+m4D7uFFQ==
    encryptionKey: MIIEogIBAAKCAQEAo2Bg77RBJuTd32ZNZZkAhnSMMvNea2FwCUgg3HgQC73dfcCiMClpJzlrO5wFOYqDM+Wnzk+8symPGMe3Kjb74JnwxnHupcYwMsqOy1Qc92iFdsyvko9+5t78Vx+JR3QARi0UwL+WKHRkMy0QXTH2eMdZgixF0+tCbyN5TKI1hZcr9jYzrNNcLgQYLJslOK1lGoPrIkLa5LtpbRXikSW2gAYmTqYz3QiOxmai1IE3GmXQmnFrAveIyEKa1NoVU6nsE07OLb/nOEHbA1wZqduxEviYgqiHNR4rvM0kfzCwN6Ri3S1yw/27v7WY+833jfe3V/G2irDVirbSuMgAMjGrpQIDAQABAoIBAAiwsbdOYUDOX7boXCmRT+PXAzYal+UiU7FKsuTHRiM5wDRWMMpbCYralQegru52na//AUQKHcFx7nik9us57X/u8E299bG/rwSknZ/XI4tNdfvxu00ScO+a4NVJiiXQ18rjzvzJtBUGy+Wk+f/bDn8yK2KvNC+njesXefZHko0+fYhs89ESNTU+ySCFjRJQxIDbU+rDP/1c8MzUxB9KKoUZKVX1BaGbjA8YZRjDSdoekwm4VAIBbhf7J6GW1sXezXdQO2rLm7UEBZQeZ6/CnRs48AH1uoNK2Gof/qcYj01WRgB4oyg0dLeWfAb0WuSrivxQhI4CK0mn3bdjiOVheqkCgYEAzAkU60/YPcvuYysPCqbIyhKLyycS1UcCwaWjxR1c4xh9KKo9AqdayDqClGximbEXZsXdfm6FStieAIb0a4s6nFynOMMexe8xK5as6p52+ecAyxidtfNqWRAoZQm7QvTNAtX6jrwJJtbpeQinCqZD0yF5ruj0B+mqyiMm0BTPDAMCgYEAzPxegtEn5P7yIusGoDv75fbMJyvdIVSCmBSWB2rN1V4onC7i1V4hGHRbmNK4o8U3tb4BgvQaHFhrNCw6h4JoT2lGTMkj9QfflgFSOjHaJoOATdzFBJZZOUR6+pGRvn1T+N5SM7isGwBbD4qM3dlG79ODRnRyiX4nQE3dF19zXTcCgYAG0jrnzwiMsFes6xCaq47E6q/Pv+OqS7B05uO9wEiNsxDkHiTiBNRNI1+gNKtrNfdxUSYhhvJf2TQXEmvzeHkiJxrUE/ngZim/qk7nnRqfKjDlmVIUdinVBmxDTHr9Nw/vi1XQFcs8iCzQBhEHkx1rXpAh39ngtdgm39v5UujFHwKBgF703XcuGpP7AgHo68XYY6UwwXu31xT0iBaZGrLO6BDaMGfBVHTQyPYCGNhfbQb4egknvp2CJIJS9z5Q6sARSe7XbqhtWMnOXuWnMQciRtMmgY4QIfgxCZ38uhdOzbv3ZKnZmyy4dImBja1SWlT+rNy2F47QrKpClT41k6CbJ97bAoGAIdOW6fJk+hvq1SrGcCW8+MUHqjRtKIndg2bgDbBNsD0eVlksv0L+p6wjIfNNQnfqlluGgyR/vEQkSmdJwvZ5d/7xdrLOkQZ6KmshK71bGWi8yDG4+qlZrO6rD2dmDcReBq1jG8/4oABTI0t9tGTkLWgw8LPJMcXcDnW9aaCg8uo=
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
