grpcServer:
    listenAddrs:
        - 127.0.0.1:4531
    tls: false
account:
    peerId: 12D3KooWE7bvg6GgoJkfYBwAQYb4a4kcp4Lwsp1ihAh7G246sZDN
    peerKey: tbcXH39s55jQorh5ShxFRcWjOr0Dmrr7zth8wuvc7DQ/2S1RbwPZZnJm/EniVXbjVrBeAgvu2sRJ8Adnh2nTDQ==
    signingKey: tbcXH39s55jQorh5ShxFRcWjOr0Dmrr7zth8wuvc7DQ/2S1RbwPZZnJm/EniVXbjVrBeAgvu2sRJ8Adnh2nTDQ==
    encryptionKey: MIIEpAIBAAKCAQEAvCsruS4iV1RE3cusy/0+ik2A4Anzl+WWNK4/bLKZZ+uIVr3dh7sp8OsRGkYF4hXscM6I7llmIJfwIurWcMbj6q8Vth0ba/KmUNdza2A0A5opbVBS5aDerbDGm+C9Q9qZr2w9xqo37P9FJ03Y1EMAer0MjZ8yUMMiVvyLcwh3hCd5AgA0xC9LJyXf2mjQY9zvf0OYei3/Y/2diNB/HGc5WpNUG/N/Z4ZyIWZemPvTF98NF+8wGGB1JLBlHwLGZ7GUg64na+ntlig58feGbH6N5K+qPyvqlz1FC7c3iZdOYClqxXAojeOGqZvEi0TvZRr20UgGeep9GUPGmMTfnW6GpwIDAQABAoIBAQCXbRZum5W/OW2CH9oa/t1JZz2DDf8eCgBqvJ8F1mRloMHDLGAOTqxd2I2W2yr42jPARDUluoPZTuxM7TdM4oGf5u5N8/aRVGBLRlb33h99lp4n/i/34xHQLSZnYuBsropnBXBhY7JF4te/3YHUr2a/X0uu3KIdJCuKXQnLtNCZY9gm/aQ6VE0FSZ/1HoqnktBRLK6HPa+L1+tCgCQ/YCuHiXd5Pwi8U16BEMqwtNAfZUBq96AhVcyDDIpO5uyWnNQWCcLVw/+6JV4w0dX9KlH3QVwWdrksnV30rQWeV+tuItemkrgHr57C4DZUvLYbCfOjuK88buaPQejCHrPADDXhAoGBAMokc+Kuu21iuKZz8TNbPss0EO6ZjEJv7tA3aTTW0b+3t2mIfOTa/KHfJwTZOHtAQllF63gx+Cty6PEVrCShAVdA+s15MRywzdWALFcAmjYTCNKneD/TMRnNiuEJZZTEMSeqCrXCLRZQxPrkjOpIxZnotJ9/jmswFmhuPHqq8oVdAoGBAO5Nm8yKaXtb+aJ8Wzpyxv5a3J0BSdkFfvj+A8AXKH+ZKmaNrz/+79msZe5t90HrqYSUhhnoSAdncxWKn6N6Lrixjpe2ddfML0SNhQWGzRFF4RLtwmLaJmgpDbUtIAdIX3MTvCDUQeRiZYw24yYFosfr3/vppsmiTnjX9YrBmFfTAoGAFAVWQP5ja+saNMpI+ngwGPo4LxmgLbheY9sJHYWlUqLElLxC+nvCB9pNSAqnsHVl3Oey8b2pQcxoy/AEk8AqnNS/wngdaCUOzfWa7qcNnwt1lT+nBlNJiq+z8KP4nqpr3+zUkLoBszMev2bBmjbI83x730xH88/YeFFqxg+GY7UCgYAAxzQZCOKrSnOYOju6ByHrNrS9toFdOg1eFsZAXFL/h6qBxzipRtXVqiBzFNzX1EMrcai2cPG7RHU1vswipoV8iOfkSu47lCkbWjLy/6uvwMCpZSlbVUcG1At9afZOz8ewAoJ8wPSuIDwgpxU6zI3phTWoBu1Kf0MuVdYxa8xpjQKBgQCLyjx0+j+TkqUai8RAwQWGOsToL+aZ7pJFIi0NS0+W5Tk0YLE/UJ07ukNlXwXig/s/H75gY8DerRaBRJhBY5NUE6q33gtQLXUZeqJPdl20lQJpYbUhsMKGhr5qZdu87AOeSLnzQ6Ukchcgsj335Vc5AFsODWf6ApbIUiVUa3DZgg==
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
