grpcServer:
    listenAddrs:
        - 127.0.0.1:4531
    tls: false
account:
    peerId: 12D3KooWNeYL4h9367PEZsnAtkBkr26oVdRbHtqApSdofMWbo9ze
    peerKey: 2X3XNEEgtVHg8LiKK5Z7o7JZpeTTyyYenoE4T6A9Eze+o5xVkfwtBVNAbahHMNX/4jz5AQUbjQreEVckEOWGnw==
    signingKey: 2X3XNEEgtVHg8LiKK5Z7o7JZpeTTyyYenoE4T6A9Eze+o5xVkfwtBVNAbahHMNX/4jz5AQUbjQreEVckEOWGnw==
    encryptionKey: MIIEowIBAAKCAQEAt5r0RtReZFB8HVO9XU9par7zneZQRZEpMuw9PLjshfwU5Q/vghxNWSUYyumetezmJaUiOg6C4ZYWkDX3f+wbyB+OCjN4keibDSMOZLudDeFJzdb4Z77Pz9rV1YhqOI+0NrArva/qoO5hPYRu1qXKZCAezFj/gto7C7IFX1RtkD74doAvefWvqE8r1MhDjDvsCkqRR9tTBqpQUvlESaij+DzAZebwHqKi9rgVsgrQddPbjruDlLKwQjyRFe9e1IDrAiDmbWWZ4V0MOMHfMdEiQ3CVdzPD0kLsaoQmp3bsjLLOx/OSrXxvFvYtznrFr2I0dRHQAU6RYxkPkryRcnD33wIDAQABAoIBAF3xxj2bmjSfzfG/kCv3XwwEamiHmNkPnlH0+JxiTnt78UEHN1iOnLEZPydMBC436canSO0F0cgVYLQnON1WdRyfsLDdhzq5FuTQ5CN8r66TcI0HCpEi2/gRk8ovg5IvTVmSKL9lDJuNfWnZolDoAbfbi4apnwtYGFAypXcSnwDnqWXyq4rIBu4bffkUbr5FxqdAcM5t8fUkhr/4qPf2gVAyz5t0fXK8Xs2frXHK7DB0JcoQ9k7xGpjEudYphsHvIYhSi5yIL/cI0AIOmOyW2p4Ct4J/BaJHqQVa2KauYr1ijDNOOmWksCH2KrxGBDu3er1/eqNjBkzGqziN4VNTawECgYEAzvh7VCU/HfZ6xnR6oVmGz+SWszKgFYWgrhAT2Je5SXznro+eaRJq98faZjN/rnriEi8U63w80x9s6mu5DHUoyT62t8KNGcYx2p7mn0okpO6vUq9qLYOpPfuqCO8zFUk4SGIUxhd1tE5XGG+Xt0SxwqX2sz6wa2KibeCCT04zXF8CgYEA4xmBcb7ZG9fn/CQam4NAsBlnMD5zYynKHCGJ9muW1PvJHLDh3NMdT6IIa/FUX0u8QsmV9r0Dkx11ATVMVvEdJ1FP93qHqjr3l+irBDYQbaDfqghFI6Fea//dsk8n9RHM2yuEr76nvPRZJfLsyzTocjLStTe2/DDAGpc/TjeoFIECgYBp1vPqgemW/vamCea0ID4qjfDqzpbCqsUSfjJH7r7X78HiqJsPjFWbRF5RKUDADyMQvXbrPWs1Y7qk3lWRI1CqKSHzMtBJP+s6q0uwZY/7r/uEQyP/BndDtTCsxPXQitL3YQDSlCii/fTYECj7lWt56LkRzJsXLyd1HPxGZe0p7QKBgDzsAbKu3PVANUaJtO2VB0x2dB0YE8I9Wq+zO5x0flECfpAIz356z/kl4ZZ7dgPegFF2XJmFWSklFNdPIfyM0CJVCNu97hj3mqYQz5fgnQWby4SElW+agYb9a87Ct1hh/w+om/69aagh8Kxif61/sv+3rJjaqmb6+P3pJx1nhtqBAoGBAIFyOM12Kch+3dEwrYCv2hR34qgcClDXbjQGhjuwl0nf5qqy4TADfQeHlDwQmpvMRTiQIlj1ipaoZqV3fDlsvgZgRxMwCkViMwsg0TR3CFR4jNC4aqrmv9fC+mTCnH3BeIGOohkTW77Zx+0PvX440MQ4Ye2YuMoioP8cRDfOmH4H
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
