grpcServer:
    listenAddrs:
        - 127.0.0.1:4532
    tls: false
account:
    peerId: 12D3KooWHcDN6uhcUukaXFwiRHs4eDac1HqwdkZ4ekFbgCUchHko
    peerKey: 9sKI3m0XUglIC8ATsRa7/2BMCxTPxRjZLqwOncWeOAFzwJIfwmia7HLIfkspSqLoWS6GRSdWtUJZ89FJmFMzvA==
    signingKey: 9sKI3m0XUglIC8ATsRa7/2BMCxTPxRjZLqwOncWeOAFzwJIfwmia7HLIfkspSqLoWS6GRSdWtUJZ89FJmFMzvA==
    encryptionKey: MIIEogIBAAKCAQEAqf3YmlwMRpnvgQPH3d+oP5VDe5vtW2QlqqE4RpWOkYt3UOg6DHxyy9AKgM1cMcLJwS+SG5ovbj3IIAQlsL28Ao3xRX5cDqYLwt6MX8nuqPZyvzmYNB+eRiPUbEONwSUFXqELI2XbqCKtqoBkAl61AsasJpGgyPaTp/QPDPIwQspO+haYX0mO6U8zCbDgzqcvdbjlPQshMP7vbgz/Gqvj6w5WHwxazMbKwp6NVYXFVIXXvz+SCuaHPEq/TbttIR5p7JIZYl95kamN6j4IHKQqSdO6HAIje8uW9nfmsjD/RAlriNAa3TIdIRhqaMA7Y72qmhJgQqe8LB7K7DTBHaWeIwIDAQABAoIBAER0zX2cA/WKmEDEXQCkyQSR/5MPwA5FzkVgl2EVaUyDdZFHc9kDZNde+FvWV4JShx0dIyGqfd9PUgBSqzr5rXT55Gev8zKS+7mGFdGdaFbyqFMJxpl3Ai4Mz8apjbRyTC9He0zOAB89l+JJwfySVyK/DySZEL7dTakdR9JW1ciPOCUW8OJgg6oyYwz5PaVMQPSGctchtp8aDxE6kfOg+G22gnsVt8W3cQT0mUnZ6LYHSi1SiP99U4+cgAKYLYd+FbMRE4ffnVQUuheCahAFbDClVa5tc5rOGUXovPr18wzl8YEYwJsI2GpFlCbJMPa2PWFBZQFqJ2X8AKYW9ruPp4ECgYEA09dhbAHX8zPEBOHpP2PY3Y0XtT0eGielFJX0A6Sa73nqupYNrltO+sKBArZFuR1xVROVjvuc3y9YzeyZi9DQNd0Khy4REMFLDD9pjEGiAmIs6e0iaLpkMm3fNa0VxDjlb9+8g7nM/Ff3uR2tZA85RTfsu/21DkSSU+zg3sq+PgkCgYEAzW02PZRK+5h2fOzDQnMrEWqJXuSk9aV5YL+jT5ilrF1wbdBOftvxHMf05YF/p33toZaC6w/Y4AeDNl+71fzGCzt2b24+ECjj1vxD+o0ubJlW0xhq2GVayDWzb2mliCZKaQHUBSMl7cXPdh7KSco+NOOEVGR2H+V/hN4KlWYCRcsCgYB6SN8U4O+OlTg29U2WaQW7xoGD/nbM9Eun2XPVUoSZbpAgCxR0rIKn3/Vm4l7XH/bW/Iod0oLYltU1cbmk6vH11dYI+H+jY2D1/fjonM5vf8qbcmale8rxDVmG+5YQAiP3c3i3tV5t4D3AnzADDYKqwUCnuCl2xgCN77RTB0fQOQKBgHPF9Aa6d5PZ9hUrvlPJ4mDbYPYY+Br1GjX7awel6OD+fCl3d3WpcPaefpeF5zK3FuC1mazubnS75ygSxiKwZdDYv0PHprSmxtlXrNwdCyfrN3Ka1USFwqcJFMpaiQ71PYR2ok4O5AZgMC7K5Yi2sV5PRznksGoDhl2UYfSW2/sHAoGAQN5rnJzEHO1PEwnoT/uh2eMTCKJrEnQkJWl0gUBnxZpNQ5FCA2zJqBkC1b90jNGU9YBL4SwnIsoyKB4z6ejsVDUhxoQohkk2w59yvC+oJBd0rQqO2QGWFFp0xoQiWaEec2KrBEn32EnuemuVhwHVPvQwCtQHzh0Txl1wPW5Y5Z4=
mongo:
    connect: mongodb://localhost:27017/?w=majority
    database: consensus
    logCollection: log
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
stream:
    timeoutMilliseconds: 1000
    maxMsgSizeMb: 256
