grpcServer:
    server:
        listenAddrs:
            - 127.0.0.1:4430
    stream:
        timeoutMilliseconds: 1000
        maxMsgSizeMb: 256
account:
    peerId: 12D3KooWKnXTtbveMDUFfeSqR5dt9a4JW66tZQXG7C7PdDh3vqGu
    peerKey: /Ou28/uU/z3BbGmkHMV5ev0mwl6lJI/NNniFlMm2gOeUHDfed/zbwYZLbPt1B0sujNx0DGKUgUTUXy/SE7biwg==
    signingKey: /Ou28/uU/z3BbGmkHMV5ev0mwl6lJI/NNniFlMm2gOeUHDfed/zbwYZLbPt1B0sujNx0DGKUgUTUXy/SE7biwg==
    encryptionKey: MIIEpAIBAAKCAQEA23AWlsGaLrUxea+x6rkpy1ByqUJKdb2oS10q0urntUCivsNb7ipo1tvM2rldn6DAIrIC1nQHdlwrakNhl/j9zfX/GdACRDEuy7pVigm78QqYwSoyZn1l717HGjXKpJpa2m9Qyo6ZNGTLcej06zuOK8yUR4gudxSV5BJ2AmMvB9v4jUdCUwROSMy0e/hDa3Cx2xV33iULF/XltoeBVDoW6yYXfsok2yH3jHUV59yqQDbZO+kAj5rO8Fd/DnmGriuQZwAwdqJBH6/NtkhbA6triS/xW7f+RoyjjA3dp7TSUscHTFW0LIUaS0ZKt6amaanT7L/Jwi/0w133wTboYPG7NQIDAQABAoIBAGRYaGv+ElSDlSFRP6nXjI4ltplB8CzRUrFL5HZY5yZSbVmQmmxZxmFiV9Y5Z9/EMbhr8LJCktsEIPJR58IIIX/amxIhtbebSgvtpIogE2qRbvL+KdgGRePlUmTg7k7BKwSyXJ6UAOkdoo7veXhMXqIWxkPDuYPIzRZjfsVut6X+j0e9W2/kK7Tx1cn07GGyEX6T9sYsrDZud9xAgDWeE3ARga+M8l3RpTi3GiM6aaz82byjtn+uROUioUSDRLeOx4lOsmTzwWs4+tcyguqC4h/01Hejs9gDsJTOZ+xsrSc+eTsj1oOmABtHcuQ6NWq4KTqV9gVAB9BEMa39k3SrzaECgYEA9kd71vAwqFp6iu3INXBuwJouV72Egwm936KGcs9/NxfXQ7R6NdKa4LiWxdIn8e7uT6+bGPxCPuUmeJ9pYandb6j6fcBcGAjPOJPg5cTtoaeXSTOBNtzaoDLM191dNkhftXAgVoz6EQXUXaGXqnUEWDCptZ8/VKO4Jbb+Zco3F30CgYEA5BljE1KiWKP3IXwfndnPFKwev8Ds6YMczCFpiCzHB4LVLAWShUQrQIcA12yIRHTvD35Vg7SwH5mM+DFd9AMNxTznz8aC7R+jXEApeaCEQqBEKakoDFMsdblT6WFwerfl5ug32IyeKglfLuOiID5M740t+6TxUR1ZjnhIx3QdMBkCgYBUANn63H6cThBSZvzNTYZZZ72668fRMndzWmplquUHk7g3Pc4ZobZ2REAZRa+eVBMxVwKeKR0net3+ctFtIJWJSqf2ULCY+hhEghxKAzvS0elGbKz8W6Su0+UPFFCA/Xq31oERRJDfUY+4SDAFUlijBCY+7wyZACcFpj9r1OepuQKBgQDAJV6ffWHC98SLkYr0pvFZgbCZaYRpJQiSMKc8jjPO8PhwD/Wgi48/2TntPsD/od1sGMkinIgs5mWpAbUag6QK/cZs8dWCuL8dS/NkQMKJeYZR7ewNjdcLCGZWV72vstBZFk9M/Q+Ta7ehwSHmtXSL60rMC+M4qFezu0HbusWHqQKBgQCNuIsiB1yS1aByY2Hw2NJyAWFIRLuv4VNm+S/+YUJzOb/cuX5rwJ+PydJj0xD5mKKq5zGhCFzGZYdheKCYC4UQKn+Zz6Iv5T/mIJU7ELy9R2/I/Jv/IQMQwDXUokbNU8p25Hxul+rI+INjoHihUFKRNL68iuGVNjQHyKQYjit+mg==
apiServer:
    server:
        listenAddrs:
            - 127.0.0.1:8080
    stream:
        timeoutMilliseconds: 1000
        maxMsgSizeMb: 256
nodes:
    - peerId: 12D3KooWKnXTtbveMDUFfeSqR5dt9a4JW66tZQXG7C7PdDh3vqGu
      address:
        - 127.0.0.1:4430
      signingKey: /Ou28/uU/z3BbGmkHMV5ev0mwl6lJI/NNniFlMm2gOeUHDfed/zbwYZLbPt1B0sujNx0DGKUgUTUXy/SE7biwg==
      encryptionKey: MIIEpAIBAAKCAQEA23AWlsGaLrUxea+x6rkpy1ByqUJKdb2oS10q0urntUCivsNb7ipo1tvM2rldn6DAIrIC1nQHdlwrakNhl/j9zfX/GdACRDEuy7pVigm78QqYwSoyZn1l717HGjXKpJpa2m9Qyo6ZNGTLcej06zuOK8yUR4gudxSV5BJ2AmMvB9v4jUdCUwROSMy0e/hDa3Cx2xV33iULF/XltoeBVDoW6yYXfsok2yH3jHUV59yqQDbZO+kAj5rO8Fd/DnmGriuQZwAwdqJBH6/NtkhbA6triS/xW7f+RoyjjA3dp7TSUscHTFW0LIUaS0ZKt6amaanT7L/Jwi/0w133wTboYPG7NQIDAQABAoIBAGRYaGv+ElSDlSFRP6nXjI4ltplB8CzRUrFL5HZY5yZSbVmQmmxZxmFiV9Y5Z9/EMbhr8LJCktsEIPJR58IIIX/amxIhtbebSgvtpIogE2qRbvL+KdgGRePlUmTg7k7BKwSyXJ6UAOkdoo7veXhMXqIWxkPDuYPIzRZjfsVut6X+j0e9W2/kK7Tx1cn07GGyEX6T9sYsrDZud9xAgDWeE3ARga+M8l3RpTi3GiM6aaz82byjtn+uROUioUSDRLeOx4lOsmTzwWs4+tcyguqC4h/01Hejs9gDsJTOZ+xsrSc+eTsj1oOmABtHcuQ6NWq4KTqV9gVAB9BEMa39k3SrzaECgYEA9kd71vAwqFp6iu3INXBuwJouV72Egwm936KGcs9/NxfXQ7R6NdKa4LiWxdIn8e7uT6+bGPxCPuUmeJ9pYandb6j6fcBcGAjPOJPg5cTtoaeXSTOBNtzaoDLM191dNkhftXAgVoz6EQXUXaGXqnUEWDCptZ8/VKO4Jbb+Zco3F30CgYEA5BljE1KiWKP3IXwfndnPFKwev8Ds6YMczCFpiCzHB4LVLAWShUQrQIcA12yIRHTvD35Vg7SwH5mM+DFd9AMNxTznz8aC7R+jXEApeaCEQqBEKakoDFMsdblT6WFwerfl5ug32IyeKglfLuOiID5M740t+6TxUR1ZjnhIx3QdMBkCgYBUANn63H6cThBSZvzNTYZZZ72668fRMndzWmplquUHk7g3Pc4ZobZ2REAZRa+eVBMxVwKeKR0net3+ctFtIJWJSqf2ULCY+hhEghxKAzvS0elGbKz8W6Su0+UPFFCA/Xq31oERRJDfUY+4SDAFUlijBCY+7wyZACcFpj9r1OepuQKBgQDAJV6ffWHC98SLkYr0pvFZgbCZaYRpJQiSMKc8jjPO8PhwD/Wgi48/2TntPsD/od1sGMkinIgs5mWpAbUag6QK/cZs8dWCuL8dS/NkQMKJeYZR7ewNjdcLCGZWV72vstBZFk9M/Q+Ta7ehwSHmtXSL60rMC+M4qFezu0HbusWHqQKBgQCNuIsiB1yS1aByY2Hw2NJyAWFIRLuv4VNm+S/+YUJzOb/cuX5rwJ+PydJj0xD5mKKq5zGhCFzGZYdheKCYC4UQKn+Zz6Iv5T/mIJU7ELy9R2/I/Jv/IQMQwDXUokbNU8p25Hxul+rI+INjoHihUFKRNL68iuGVNjQHyKQYjit+mg==
      types:
        - tree
    - peerId: 12D3KooWKgVN2kW8xw5Uvm2sLUnkeUNQYAvcWvF58maTzev7FjPi
      address:
        - 127.0.0.1:4431
      signingKey: ckI1ThxMQmAWH48so5jT614HNg4VppB/3jTfh1cdrzSSkFuVPiGzSDJcsgFLsRGW2WT0a8ymqtc4hog5Z4mdfQ==
      encryptionKey: MIIEpAIBAAKCAQEAwQcHwXkTynIvU5PfTn9kaQEb5Zzz8eHl/uO1srbWI0hM+sIvhOq/ahYuhDlai0mAhRFQIvb6QRnWzCp3qvMH8+j8ls83BKV4hfxuS+SR/Y/LonW+WeLljiloMM5ju9tjw1iSslUK6z7d0HSLppQCCjMP+v3kKjx24qJ2T+2N1MAMbdt+S5c2P2jBUJVSvQbZ1AVuZTEzDau//+cZzV47lsODrVZ2SxW/KAAKA9xIJSIwBFyIqya54FDlrsy4HMcThxUbmcqy0Ou3bRjPR2f9A6QaNDNlolPhW1Z4gs+MTQOXJyAj2vdKwNKPwr8X6wyUtN4v8MiJt2yl4h3EVSVkGQIDAQABAoIBAQCak4iwdMdWfa5MncRb1kSQmiS+8bug3igSwEOHREejpYiP3uWy6VI0IGNL26oYlNnotf6YoXOyooCSqwd9zHV37AIquvHyNJiZo5aoC/ilN3v5M5Ul4j+2Yo5fV0gi7gOsMcf4K4Y88PEst8gFs80WYeHQO3V2JUmHIFbilvfXgDfQNuKlHXgWq5kNNCxIobGpuP70Vvn1ANkDXLt+bU8RCbmBYFUZ/4HUeawf2NX+Xn5T1NFpheA68hAGprFQu6CuEsM34TtPZwH5SxyvOmA218nQbtq5fNLUgHZdq/uAeQyq7E8kxyOMEbx7m1UYtxDjwowBQgQd1dOtm3wTeQdpAoGBANjs7B0IW/B3TY6mRipcKtTYMVJ+M6AKu7etTkcmM6NpLGaIL9HqNP/a8PoNmHzVOBPJlC96ChQAvcULe+SKBL4L5g1T+k7OQvHEFMwzkFgs/HxjvQE9b1xX1Qyp+e9H7yvrcJhvRPbj3LLp7vunHL9dEm4/PFNKgCFExNsiv8WvAoGBAOPMGXtAethDYZE7vdlD55GdhsgklCmF3YQcraWsZrswj9paIBV8FWtVZIUDdaqOasPwT8L2NdajYWXXcmLlvxkOQQx7+cJG4SdLRwEz531rXvtcYrWPYYwjf37DQMi2qRmvZ0Oc/atitwN7mQ4wCMzZ+CV04HJTjK4eRfeDeyy3AoGAFbQWp4z3jeaR1uzh5kkUa/k5bhR8W83XHDh1tX6n+fiC3btQdYMmTFb+dzY3BH5cvvYTInDmYzvzwKw2eBYrBUyxdrHpQEs4vXGt1wRts7TEijl8ZoxcAPQ0t7Cl9f/PeSh0OnwffUgtA6WOKJV+tdK9DlS7V2YDzdBQldAzObcCgYAbjn0mo844iy4qW4fD2KsSunOrkoE55K+/Y5i+CfUDgARm7bAj6TbOHS5jyN9bGo9f1JpRg2dP58PIhh+YRyKu7UKBOB4mmlxyXHDifFzslyiOT8bBH+80/LZXp1cW8MHUEZv0WfF14iMxkKobRURLQ7L5FQJx0hmalp7wKj+kUQKBgQCEavx+ELQu1M22t4Kk1MOI1zEsrG4D+hjACmoWQsIjMqi5x+9vPJNshrO9vbYljjsIt4EOfqBB88oMepCesVHwbX3+/j7Yb48pmf2vZNcQ+SFozJqnCqYNQiWMtNXWT312NVdzkvpTlA0e1vaauwJjtetRnYDJUOPjc8BrdKsftw==
      types:
        - tree
    - peerId: 12D3KooWCUPYuMnQhu9yREJgQyjcz8zWY83rZGmDLwb9YR6QkbZX
      address:
        - 127.0.0.1:4432
      signingKey: EqD0bdvO2E9+i29hfJTMtae8Zw8Dgnb/KanLSg59K7YndQHdxxvtVUljy3htlXd7dGKfEuJ7EglVHdNxzg5q7g==
      encryptionKey: MIIEpAIBAAKCAQEAuOwKfzHLrm94jH4PElKfkB9geQ5OhtdbcS4K3TeyZ5xU0hi0TiXxOiHQOCg2uO7B/fnQcAArUBvPNa4QOvNuWRY+246FHYBxCJvJdfOpwirQbQ2l5iqR13rpSAELnF/zB4XMQa6wGVhsgWipvY9PUrLF6RwpeeBu9OtpVaA2oUiUXyD+v1f4dNXjZqrTKS9IycksGEEI4knEfG421K862BRty94pVWfqv/ZgpJUQZiWLX9CSbAdvjoHxOdm96VhMjTBw3oyv7hTr/zQR9y77OMFwOOBtn4QWXSS54r89inoksgGjH5cProhR+V4QZ4962TGsnc92j+IjtlxI/o3CuQIDAQABAoIBACyLl5+6NBFqAsT9HM5SHuPN2yRuINZ0jC+AYteVMiGpU/lkQBLPKwPQ32KXtU7pHMv8YIyKTeS3Pjv1GS3KNBu7sxqag1Bu/0uOk4IZVxxRyfFrJzqBqK4aipVwwwZBSr7WKTTtSrhgR4sI1lK2ceo+7FPSF9+nA7N1/eLFfENvWegG9cM9G1162f1ypTmTKB6zvyEhrMnpw5IWGiyL41Pbn7Q6qMxJCMedJn40UWwZ+K04StxcX0MdPqiRC1mhEECF23y/Yu3QYVlyAR/Ya6POPK+Y/PQhvYuA8gMbdJgM/BpFntqqJx6nf9ojZjmkpFytHuKojDP+SOYSvifGSzECgYEA85YGa9DNHeEGU7e7U6iReHn0Cy1ZlDl4q/E1tyOSY1tpuTdiIYNLZAmx/ZDLj7y8NcNwK44CWhNGUlsTGOL0wrsFefH6tJOLLklTgwo6gnFFeNKUaTrZMQhu1Rf6fruO6yUHe34EgDnMIclx3+bXpZmWGVVOXLx7e/gQfDiRg3UCgYEAwlimHW2pJshQdCCyIFPvf36FK7xNiTIGy4VW8q8ulX4UESioxQtv8Irf5UCo1WpTSNA8RYRPU4gZnp0jkBydNDU2bdNGiN3IySU99/2dtYEHPJAferwXoOVdSCVXw2fGyQZK6GaciWDP3bgZdVKBSGBCN30eJ2PDVKni2NiHbbUCgYAdPHKE2kjkPy/9OF45ik/7f9e0x7qqucMsEAV8d76IQl6MJoOWtiWEWk2Mu6ZTGDoW0eBSufa6TPnxxJCkOglangvoOQz4Q4U/BvoJDl87bNED0XKStsd+xR5YYUplj6l1u7oMLnHn2ggQPhd24kQb0jVb0QtYwh6oIHwKDNgaSQKBgQCuTYeeuS2ORPYzUOexKtaQSE7z7My1kZKakhprSkbDePJSeV70as+Ys1UfbaB+1/+ePHTx/DqRNm2T3md45tDvdBI+6dBHDHL6RFaRxnrdwL1WygQRtgSTH2NMQ4G1Fawpu2UPjogyhguoVWcv3DFrUjnRPnv+4/DaTAvSZFECSQKBgQDh6g0n+MIknDo89ffCmIuD5qkPi7GYYGBfQ7HHHq5dUXazN6+vKazgGEJo72MU4ZlHl/U33MoMuuVP2cBEYJx8iMaP7ze8jUWVRA7rzg4A2ayBCOQxpBehEBhD1yEBPKO5PVTYV0a3BiM4tQLLPuoh5QcB7ANwmZkFdLpizLqn2A==
      types:
        - tree
    - peerId: 12D3KooWNT4hbNKXeFuDtdQ13ZbhQ1oJJ2AVWgAQVRrCj6Zb5wxk
      address:
        - 127.0.0.1:4530
      types:
        - consensus
    - peerId: 12D3KooWNQZjL4H82u9qdjpWFBFjFdZyTqvgXT6dajkJuRn9yE8H
      address:
        - 127.0.0.1:4531
      types:
        - consensus
    - peerId: 12D3KooWR5tEHzEqVjQas8PfhsGjWMooTWXsryDUz8HXWYnQhczf
      address:
        - 127.0.0.1:4532
      types:
        - consensus
    - peerId: 12D3KooWQxiZ5a7vcy4DTJa8Gy1eVUmwb5ojN4SrJC9Rjxzigw6C
      address:
        - 127.0.0.1:4730
      types:
        - file
space:
    gcTTL: 60
    syncPeriod: 20
storage:
    path: db/node/1/data
metric:
    addr: ""
log:
    production: false
    defaultLevel: ""
    namedLevels: {}
