anytype:
    swarmKey: /key/swarm/psk/1.0.0/base16/209992e611c27d5dce8fbd2e7389f6b51da9bee980992ef60739460b536139ec
grpcServer:
    listenAddrs:
        - 127.0.0.1:4432
    tls: false
account:
    peerId: 12D3KooWG7bXBK1NdyyWT4bnGUQjbe9kpVzsZSm97MQVR13zRx4M
    signingKey: dm6xzcZCMOEs7h8dOJgMqcFB+EyZMXBjjOFzAqg7GeldkBfDFG75NB1gVc25MhokEeScnh8WAWEvy4YUikPJDg==
    encryptionKey: MIIEpQIBAAKCAQEA7habKY4w6fYFTneChju1kFG999EeZG1bXQlNbeV9Wbsg4Hy1FDlZUNf7QxQDxCKGnSHLySt/FOdQvp007WcLIefwgaIr3vJQn1/QBKiYiKytE4qURMwum52FHAtw0Xnd8TjKPynei9boEx5nQ8wRA786sh1BLd9oWg/WZgZZ8fwMZDQTWSdn7bQh5fQcuvnd4MQD4A63JQ+0JitF8g9tLzH5n2IvbicXjkvY31rhf4lo8XeHtkKEkerxhBUm4Q3G0hiCD0xmQqBSNeaRa5dqxplFJmWxyvJM87ugsRFlntHEVpHjnhI8ZLRf/4wDlXqYCQ3pI0V5dSdI2vL2Lynx6QIDAQABAoIBAQC1XylChdyDTnSKawZWxcOxtmOWFosljB0uibifgFR2d9Q6zyWOy4VbzbzOQ7/+uSJ9L1Kz5FvCC9j57H52X6oeYTdZObZb95ItZurrsZfJfmm22jnLExRqXZwaWijOmxzU9yMy7O1o8AUJE38tKZbImPPY3epaTLeM7EWyoSIB8T0G4J99oZBGmjsuUtAVUDzpfuvAmqs8/tSzzOW47HgxCZJJLdmQeiCEwBmKyeMcI5iUfxDFZcTB2yReDNPPWzrkn6HybwtN8f114TvV1sEZpozcnJrhB8bxF34HKEC15j/iXlobH90YvKIdVAOJDGjMJZcQc5B8UkfHeSqf6b+BAoGBAP/4K8ZzwVKU80pbN54ExpoUD5k8L6SREUIjUSpecJ76bdDtbZij2rJ6D9pPKLr5PVEMVtbpcIOY4FBpsWhzkcZ2LW9w7p27DMXAm9jcf15w/WZJAIr5D46qBMAP4hvBm5adsii6HJLBauGz7sLz2uRnQCHQaknLo24mltZ3nP6RAoGBAO4d42ENPusmatInr0oA52jlC/h6yUFLCBoziU2JYm0kNcwVzmeIIIxH5yZtL9viwuNUoZQzWIM6dgxVFyb5qO3QHTqYAL9xgVkxMpyrSHBCwuJxcH8oDu8UH2UDVmna4PUdSc8tpQtAKPGKWdWTOG5G9Fu4BbcwCT7dcCWjmhnZAoGBAOtk4XTuTNHSEu7Fdh9GixF082dbFwFDO1jUO7c4BF/fM5BYWFpwDRXm9J8x/uX7gW0AaPfY09ThiR/KIxFIfr3BPkVm2LmLI9LULz4+gI9sX0xqRCqJosnzBs1NjgUyhg/707Rqew5m+xC3NRJpyVoUrcCq9qQItrH8oOh4NZNRAoGBAN7rKDVxmxe17Yc1E8tqMTpoQ96pxMPVpI4y9TWbioO2xI59U7BlJmNt5R56VbW7AsykLGh78T9Zea5t8rDQRa/th4+VQg34Cyoe/szhJX3DYoNvw+um6uQzqHh+uWV8PeH7O2Az0TFJLYuDBDsICmpjDtzW2LL4y48I67axBNFxAoGAHIn7/XyHYzkCilSDa1BG9TMYErdCehhVjlqFJ2rvQNnQN6NOfFvln3YN0dHxrKNmUzMsn9ZcV/36AIOgEmHeLVD0KUB50MCwBPtcbGN053rXbqx8AQUkPA7/+ERXiLcEELftFn37NXDv4Wj51w92tnUwke80J4lDos87Nx91w70=
apiServer:
    port: "8082"
nodes:
    - peerId: 12D3KooWFVGSu8MfoUnPmUGPpJKNpxaM7mezZ98V1ERGEQbTWjnE
      address: 127.0.0.1:4430
    - peerId: 12D3KooWMPgKGCLtNkmANzwHAnymEMCggS6csXuDroUFqb63FizD
      address: 127.0.0.1:4431
    - peerId: 12D3KooWG7bXBK1NdyyWT4bnGUQjbe9kpVzsZSm97MQVR13zRx4M
      address: 127.0.0.1:4432
    - peerId: 12D3KooWKZcPNMmMqi6PZFjUkZqrFXXUYLpzoHBjbHLPojkuj4xp
      address: 127.0.0.1:4530
      isConsensus: true
    - peerId: 12D3KooWGVroVVTuhc7GcnYZ3T9RmvuB4LWwqQRgvEMWQWPQqTy8
      address: 127.0.0.1:4531
      isConsensus: true
    - peerId: 12D3KooWDLvgBnuUnuLea8QZBEA8MSffmWoNj8JFto3N5AqUDV44
      address: 127.0.0.1:4532
      isConsensus: true
space:
    gcTTL: 60
    syncPeriod: 10
