// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: commonfile/fileproto/protos/file.proto

package fileproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCodes int32

const (
	ErrCodes_Unexpected        ErrCodes = 0
	ErrCodes_CIDNotFound       ErrCodes = 1
	ErrCodes_Forbidden         ErrCodes = 2
	ErrCodes_LimitExceeded     ErrCodes = 3
	ErrCodes_QuerySizeExceeded ErrCodes = 4
	ErrCodes_WrongHash         ErrCodes = 5
	ErrCodes_NotEnoughSpace    ErrCodes = 6
	ErrCodes_ErrorOffset       ErrCodes = 200
)

// Enum value maps for ErrCodes.
var (
	ErrCodes_name = map[int32]string{
		0:   "Unexpected",
		1:   "CIDNotFound",
		2:   "Forbidden",
		3:   "LimitExceeded",
		4:   "QuerySizeExceeded",
		5:   "WrongHash",
		6:   "NotEnoughSpace",
		200: "ErrorOffset",
	}
	ErrCodes_value = map[string]int32{
		"Unexpected":        0,
		"CIDNotFound":       1,
		"Forbidden":         2,
		"LimitExceeded":     3,
		"QuerySizeExceeded": 4,
		"WrongHash":         5,
		"NotEnoughSpace":    6,
		"ErrorOffset":       200,
	}
)

func (x ErrCodes) Enum() *ErrCodes {
	p := new(ErrCodes)
	*p = x
	return p
}

func (x ErrCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_commonfile_fileproto_protos_file_proto_enumTypes[0].Descriptor()
}

func (ErrCodes) Type() protoreflect.EnumType {
	return &file_commonfile_fileproto_protos_file_proto_enumTypes[0]
}

func (x ErrCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCodes.Descriptor instead.
func (ErrCodes) EnumDescriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{0}
}

type AvailabilityStatus int32

const (
	AvailabilityStatus_NotExists     AvailabilityStatus = 0
	AvailabilityStatus_Exists        AvailabilityStatus = 1
	AvailabilityStatus_ExistsInSpace AvailabilityStatus = 2
)

// Enum value maps for AvailabilityStatus.
var (
	AvailabilityStatus_name = map[int32]string{
		0: "NotExists",
		1: "Exists",
		2: "ExistsInSpace",
	}
	AvailabilityStatus_value = map[string]int32{
		"NotExists":     0,
		"Exists":        1,
		"ExistsInSpace": 2,
	}
)

func (x AvailabilityStatus) Enum() *AvailabilityStatus {
	p := new(AvailabilityStatus)
	*p = x
	return p
}

func (x AvailabilityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailabilityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_commonfile_fileproto_protos_file_proto_enumTypes[1].Descriptor()
}

func (AvailabilityStatus) Type() protoreflect.EnumType {
	return &file_commonfile_fileproto_protos_file_proto_enumTypes[1]
}

func (x AvailabilityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvailabilityStatus.Descriptor instead.
func (AvailabilityStatus) EnumDescriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{1}
}

type Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ok) Reset() {
	*x = Ok{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{0}
}

type BlockGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	Cid           []byte                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Wait          bool                   `protobuf:"varint,3,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockGetRequest) Reset() {
	*x = BlockGetRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockGetRequest) ProtoMessage() {}

func (x *BlockGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockGetRequest.ProtoReflect.Descriptor instead.
func (*BlockGetRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{1}
}

func (x *BlockGetRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *BlockGetRequest) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *BlockGetRequest) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

type BlockGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           []byte                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockGetResponse) Reset() {
	*x = BlockGetResponse{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockGetResponse) ProtoMessage() {}

func (x *BlockGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockGetResponse.ProtoReflect.Descriptor instead.
func (*BlockGetResponse) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{2}
}

func (x *BlockGetResponse) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *BlockGetResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlockPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=fileId,proto3" json:"fileId,omitempty"`
	Cid           []byte                 `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPushRequest) Reset() {
	*x = BlockPushRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPushRequest) ProtoMessage() {}

func (x *BlockPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPushRequest.ProtoReflect.Descriptor instead.
func (*BlockPushRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{3}
}

func (x *BlockPushRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *BlockPushRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *BlockPushRequest) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *BlockPushRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlockPushManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	FileBlocks    []*FileBlock           `protobuf:"bytes,2,rep,name=fileBlocks,proto3" json:"fileBlocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPushManyRequest) Reset() {
	*x = BlockPushManyRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPushManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPushManyRequest) ProtoMessage() {}

func (x *BlockPushManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPushManyRequest.ProtoReflect.Descriptor instead.
func (*BlockPushManyRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{4}
}

func (x *BlockPushManyRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *BlockPushManyRequest) GetFileBlocks() []*FileBlock {
	if x != nil {
		return x.FileBlocks
	}
	return nil
}

type FileBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	Cid           []byte                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileBlock) Reset() {
	*x = FileBlock{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBlock) ProtoMessage() {}

func (x *FileBlock) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileBlock.ProtoReflect.Descriptor instead.
func (*FileBlock) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{5}
}

func (x *FileBlock) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileBlock) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *FileBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlocksCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	Cids          [][]byte               `protobuf:"bytes,2,rep,name=cids,proto3" json:"cids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocksCheckRequest) Reset() {
	*x = BlocksCheckRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocksCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksCheckRequest) ProtoMessage() {}

func (x *BlocksCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksCheckRequest.ProtoReflect.Descriptor instead.
func (*BlocksCheckRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{6}
}

func (x *BlocksCheckRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *BlocksCheckRequest) GetCids() [][]byte {
	if x != nil {
		return x.Cids
	}
	return nil
}

type BlocksCheckResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BlocksAvailability []*BlockAvailability   `protobuf:"bytes,1,rep,name=blocksAvailability,proto3" json:"blocksAvailability,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BlocksCheckResponse) Reset() {
	*x = BlocksCheckResponse{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocksCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksCheckResponse) ProtoMessage() {}

func (x *BlocksCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksCheckResponse.ProtoReflect.Descriptor instead.
func (*BlocksCheckResponse) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{7}
}

func (x *BlocksCheckResponse) GetBlocksAvailability() []*BlockAvailability {
	if x != nil {
		return x.BlocksAvailability
	}
	return nil
}

type BlockAvailability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           []byte                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Status        AvailabilityStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=filesync.AvailabilityStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockAvailability) Reset() {
	*x = BlockAvailability{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAvailability) ProtoMessage() {}

func (x *BlockAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAvailability.ProtoReflect.Descriptor instead.
func (*BlockAvailability) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{8}
}

func (x *BlockAvailability) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *BlockAvailability) GetStatus() AvailabilityStatus {
	if x != nil {
		return x.Status
	}
	return AvailabilityStatus_NotExists
}

type BlocksBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=fileId,proto3" json:"fileId,omitempty"`
	Cids          [][]byte               `protobuf:"bytes,3,rep,name=cids,proto3" json:"cids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocksBindRequest) Reset() {
	*x = BlocksBindRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocksBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksBindRequest) ProtoMessage() {}

func (x *BlocksBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksBindRequest.ProtoReflect.Descriptor instead.
func (*BlocksBindRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{9}
}

func (x *BlocksBindRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *BlocksBindRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *BlocksBindRequest) GetCids() [][]byte {
	if x != nil {
		return x.Cids
	}
	return nil
}

type FilesDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	FileIds       []string               `protobuf:"bytes,2,rep,name=fileIds,proto3" json:"fileIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesDeleteRequest) Reset() {
	*x = FilesDeleteRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesDeleteRequest) ProtoMessage() {}

func (x *FilesDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesDeleteRequest.ProtoReflect.Descriptor instead.
func (*FilesDeleteRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{10}
}

func (x *FilesDeleteRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *FilesDeleteRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type FilesDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesDeleteResponse) Reset() {
	*x = FilesDeleteResponse{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesDeleteResponse) ProtoMessage() {}

func (x *FilesDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesDeleteResponse.ProtoReflect.Descriptor instead.
func (*FilesDeleteResponse) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{11}
}

type FilesInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	FileIds       []string               `protobuf:"bytes,2,rep,name=fileIds,proto3" json:"fileIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesInfoRequest) Reset() {
	*x = FilesInfoRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesInfoRequest) ProtoMessage() {}

func (x *FilesInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesInfoRequest.ProtoReflect.Descriptor instead.
func (*FilesInfoRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{12}
}

func (x *FilesInfoRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *FilesInfoRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type FilesInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesInfo     []*FileInfo            `protobuf:"bytes,1,rep,name=filesInfo,proto3" json:"filesInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesInfoResponse) Reset() {
	*x = FilesInfoResponse{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesInfoResponse) ProtoMessage() {}

func (x *FilesInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesInfoResponse.ProtoReflect.Descriptor instead.
func (*FilesInfoResponse) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{13}
}

func (x *FilesInfoResponse) GetFilesInfo() []*FileInfo {
	if x != nil {
		return x.FilesInfo
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	UsageBytes    uint64                 `protobuf:"varint,2,opt,name=usageBytes,proto3" json:"usageBytes,omitempty"`
	CidsCount     uint32                 `protobuf:"varint,3,opt,name=cidsCount,proto3" json:"cidsCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{14}
}

func (x *FileInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileInfo) GetUsageBytes() uint64 {
	if x != nil {
		return x.UsageBytes
	}
	return 0
}

func (x *FileInfo) GetCidsCount() uint32 {
	if x != nil {
		return x.CidsCount
	}
	return 0
}

type FilesGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesGetRequest) Reset() {
	*x = FilesGetRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesGetRequest) ProtoMessage() {}

func (x *FilesGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesGetRequest.ProtoReflect.Descriptor instead.
func (*FilesGetRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{15}
}

func (x *FilesGetRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type FilesGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesGetResponse) Reset() {
	*x = FilesGetResponse{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesGetResponse) ProtoMessage() {}

func (x *FilesGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesGetResponse.ProtoReflect.Descriptor instead.
func (*FilesGetResponse) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{16}
}

func (x *FilesGetResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{17}
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceIds      []string               `protobuf:"bytes,1,rep,name=spaceIds,proto3" json:"spaceIds,omitempty"`
	AllowWrite    bool                   `protobuf:"varint,2,opt,name=allowWrite,proto3" json:"allowWrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{18}
}

func (x *CheckResponse) GetSpaceIds() []string {
	if x != nil {
		return x.SpaceIds
	}
	return nil
}

func (x *CheckResponse) GetAllowWrite() bool {
	if x != nil {
		return x.AllowWrite
	}
	return false
}

type SpaceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceInfoRequest) Reset() {
	*x = SpaceInfoRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceInfoRequest) ProtoMessage() {}

func (x *SpaceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceInfoRequest.ProtoReflect.Descriptor instead.
func (*SpaceInfoRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{19}
}

func (x *SpaceInfoRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type SpaceInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LimitBytes      uint64                 `protobuf:"varint,1,opt,name=limitBytes,proto3" json:"limitBytes,omitempty"`
	TotalUsageBytes uint64                 `protobuf:"varint,2,opt,name=totalUsageBytes,proto3" json:"totalUsageBytes,omitempty"`
	CidsCount       uint64                 `protobuf:"varint,3,opt,name=cidsCount,proto3" json:"cidsCount,omitempty"`
	FilesCount      uint64                 `protobuf:"varint,4,opt,name=filesCount,proto3" json:"filesCount,omitempty"`
	SpaceUsageBytes uint64                 `protobuf:"varint,5,opt,name=spaceUsageBytes,proto3" json:"spaceUsageBytes,omitempty"`
	SpaceId         string                 `protobuf:"bytes,6,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SpaceInfoResponse) Reset() {
	*x = SpaceInfoResponse{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceInfoResponse) ProtoMessage() {}

func (x *SpaceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceInfoResponse.ProtoReflect.Descriptor instead.
func (*SpaceInfoResponse) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{20}
}

func (x *SpaceInfoResponse) GetLimitBytes() uint64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

func (x *SpaceInfoResponse) GetTotalUsageBytes() uint64 {
	if x != nil {
		return x.TotalUsageBytes
	}
	return 0
}

func (x *SpaceInfoResponse) GetCidsCount() uint64 {
	if x != nil {
		return x.CidsCount
	}
	return 0
}

func (x *SpaceInfoResponse) GetFilesCount() uint64 {
	if x != nil {
		return x.FilesCount
	}
	return 0
}

func (x *SpaceInfoResponse) GetSpaceUsageBytes() uint64 {
	if x != nil {
		return x.SpaceUsageBytes
	}
	return 0
}

func (x *SpaceInfoResponse) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type AccountInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfoRequest) Reset() {
	*x = AccountInfoRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoRequest) ProtoMessage() {}

func (x *AccountInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoRequest.ProtoReflect.Descriptor instead.
func (*AccountInfoRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{21}
}

type AccountInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the shared limit excluding isolated spaces
	LimitBytes      uint64               `protobuf:"varint,1,opt,name=limitBytes,proto3" json:"limitBytes,omitempty"`
	TotalUsageBytes uint64               `protobuf:"varint,2,opt,name=totalUsageBytes,proto3" json:"totalUsageBytes,omitempty"`
	TotalCidsCount  uint64               `protobuf:"varint,3,opt,name=totalCidsCount,proto3" json:"totalCidsCount,omitempty"`
	Spaces          []*SpaceInfoResponse `protobuf:"bytes,4,rep,name=spaces,proto3" json:"spaces,omitempty"`
	// the total limit including isolated spaces
	AccountLimitBytes uint64 `protobuf:"varint,5,opt,name=accountLimitBytes,proto3" json:"accountLimitBytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AccountInfoResponse) Reset() {
	*x = AccountInfoResponse{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoResponse) ProtoMessage() {}

func (x *AccountInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoResponse.ProtoReflect.Descriptor instead.
func (*AccountInfoResponse) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{22}
}

func (x *AccountInfoResponse) GetLimitBytes() uint64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

func (x *AccountInfoResponse) GetTotalUsageBytes() uint64 {
	if x != nil {
		return x.TotalUsageBytes
	}
	return 0
}

func (x *AccountInfoResponse) GetTotalCidsCount() uint64 {
	if x != nil {
		return x.TotalCidsCount
	}
	return 0
}

func (x *AccountInfoResponse) GetSpaces() []*SpaceInfoResponse {
	if x != nil {
		return x.Spaces
	}
	return nil
}

func (x *AccountInfoResponse) GetAccountLimitBytes() uint64 {
	if x != nil {
		return x.AccountLimitBytes
	}
	return 0
}

type AccountLimitSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountLimitSetRequest) Reset() {
	*x = AccountLimitSetRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLimitSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLimitSetRequest) ProtoMessage() {}

func (x *AccountLimitSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLimitSetRequest.ProtoReflect.Descriptor instead.
func (*AccountLimitSetRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{23}
}

func (x *AccountLimitSetRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *AccountLimitSetRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SpaceLimitSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceLimitSetRequest) Reset() {
	*x = SpaceLimitSetRequest{}
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceLimitSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceLimitSetRequest) ProtoMessage() {}

func (x *SpaceLimitSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonfile_fileproto_protos_file_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceLimitSetRequest.ProtoReflect.Descriptor instead.
func (*SpaceLimitSetRequest) Descriptor() ([]byte, []int) {
	return file_commonfile_fileproto_protos_file_proto_rawDescGZIP(), []int{24}
}

func (x *SpaceLimitSetRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SpaceLimitSetRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_commonfile_fileproto_protos_file_proto protoreflect.FileDescriptor

const file_commonfile_fileproto_protos_file_proto_rawDesc = "" +
	"\n" +
	"&commonfile/fileproto/protos/file.proto\x12\bfilesync\"\x04\n" +
	"\x02Ok\"Q\n" +
	"\x0fBlockGetRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\fR\x03cid\x12\x12\n" +
	"\x04wait\x18\x03 \x01(\bR\x04wait\"8\n" +
	"\x10BlockGetResponse\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"j\n" +
	"\x10BlockPushRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x16\n" +
	"\x06fileId\x18\x02 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03cid\x18\x03 \x01(\fR\x03cid\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"e\n" +
	"\x14BlockPushManyRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x123\n" +
	"\n" +
	"fileBlocks\x18\x02 \x03(\v2\x13.filesync.FileBlockR\n" +
	"fileBlocks\"I\n" +
	"\tFileBlock\x12\x16\n" +
	"\x06fileId\x18\x01 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\fR\x03cid\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"B\n" +
	"\x12BlocksCheckRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04cids\x18\x02 \x03(\fR\x04cids\"b\n" +
	"\x13BlocksCheckResponse\x12K\n" +
	"\x12blocksAvailability\x18\x01 \x03(\v2\x1b.filesync.BlockAvailabilityR\x12blocksAvailability\"[\n" +
	"\x11BlockAvailability\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.filesync.AvailabilityStatusR\x06status\"Y\n" +
	"\x11BlocksBindRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x16\n" +
	"\x06fileId\x18\x02 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04cids\x18\x03 \x03(\fR\x04cids\"H\n" +
	"\x12FilesDeleteRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x18\n" +
	"\afileIds\x18\x02 \x03(\tR\afileIds\"\x15\n" +
	"\x13FilesDeleteResponse\"F\n" +
	"\x10FilesInfoRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x18\n" +
	"\afileIds\x18\x02 \x03(\tR\afileIds\"E\n" +
	"\x11FilesInfoResponse\x120\n" +
	"\tfilesInfo\x18\x01 \x03(\v2\x12.filesync.FileInfoR\tfilesInfo\"`\n" +
	"\bFileInfo\x12\x16\n" +
	"\x06fileId\x18\x01 \x01(\tR\x06fileId\x12\x1e\n" +
	"\n" +
	"usageBytes\x18\x02 \x01(\x04R\n" +
	"usageBytes\x12\x1c\n" +
	"\tcidsCount\x18\x03 \x01(\rR\tcidsCount\"+\n" +
	"\x0fFilesGetRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\"*\n" +
	"\x10FilesGetResponse\x12\x16\n" +
	"\x06fileId\x18\x01 \x01(\tR\x06fileId\"\x0e\n" +
	"\fCheckRequest\"K\n" +
	"\rCheckResponse\x12\x1a\n" +
	"\bspaceIds\x18\x01 \x03(\tR\bspaceIds\x12\x1e\n" +
	"\n" +
	"allowWrite\x18\x02 \x01(\bR\n" +
	"allowWrite\",\n" +
	"\x10SpaceInfoRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\"\xdf\x01\n" +
	"\x11SpaceInfoResponse\x12\x1e\n" +
	"\n" +
	"limitBytes\x18\x01 \x01(\x04R\n" +
	"limitBytes\x12(\n" +
	"\x0ftotalUsageBytes\x18\x02 \x01(\x04R\x0ftotalUsageBytes\x12\x1c\n" +
	"\tcidsCount\x18\x03 \x01(\x04R\tcidsCount\x12\x1e\n" +
	"\n" +
	"filesCount\x18\x04 \x01(\x04R\n" +
	"filesCount\x12(\n" +
	"\x0fspaceUsageBytes\x18\x05 \x01(\x04R\x0fspaceUsageBytes\x12\x18\n" +
	"\aspaceId\x18\x06 \x01(\tR\aspaceId\"\x14\n" +
	"\x12AccountInfoRequest\"\xea\x01\n" +
	"\x13AccountInfoResponse\x12\x1e\n" +
	"\n" +
	"limitBytes\x18\x01 \x01(\x04R\n" +
	"limitBytes\x12(\n" +
	"\x0ftotalUsageBytes\x18\x02 \x01(\x04R\x0ftotalUsageBytes\x12&\n" +
	"\x0etotalCidsCount\x18\x03 \x01(\x04R\x0etotalCidsCount\x123\n" +
	"\x06spaces\x18\x04 \x03(\v2\x1b.filesync.SpaceInfoResponseR\x06spaces\x12,\n" +
	"\x11accountLimitBytes\x18\x05 \x01(\x04R\x11accountLimitBytes\"J\n" +
	"\x16AccountLimitSetRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"F\n" +
	"\x14SpaceLimitSetRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit*\x99\x01\n" +
	"\bErrCodes\x12\x0e\n" +
	"\n" +
	"Unexpected\x10\x00\x12\x0f\n" +
	"\vCIDNotFound\x10\x01\x12\r\n" +
	"\tForbidden\x10\x02\x12\x11\n" +
	"\rLimitExceeded\x10\x03\x12\x15\n" +
	"\x11QuerySizeExceeded\x10\x04\x12\r\n" +
	"\tWrongHash\x10\x05\x12\x12\n" +
	"\x0eNotEnoughSpace\x10\x06\x12\x10\n" +
	"\vErrorOffset\x10\xc8\x01*B\n" +
	"\x12AvailabilityStatus\x12\r\n" +
	"\tNotExists\x10\x00\x12\n" +
	"\n" +
	"\x06Exists\x10\x01\x12\x11\n" +
	"\rExistsInSpace\x10\x022\xe9\x06\n" +
	"\x04File\x12A\n" +
	"\bBlockGet\x12\x19.filesync.BlockGetRequest\x1a\x1a.filesync.BlockGetResponse\x125\n" +
	"\tBlockPush\x12\x1a.filesync.BlockPushRequest\x1a\f.filesync.Ok\x12=\n" +
	"\rBlockPushMany\x12\x1e.filesync.BlockPushManyRequest\x1a\f.filesync.Ok\x12J\n" +
	"\vBlocksCheck\x12\x1c.filesync.BlocksCheckRequest\x1a\x1d.filesync.BlocksCheckResponse\x127\n" +
	"\n" +
	"BlocksBind\x12\x1b.filesync.BlocksBindRequest\x1a\f.filesync.Ok\x12J\n" +
	"\vFilesDelete\x12\x1c.filesync.FilesDeleteRequest\x1a\x1d.filesync.FilesDeleteResponse\x12D\n" +
	"\tFilesInfo\x12\x1a.filesync.FilesInfoRequest\x1a\x1b.filesync.FilesInfoResponse\x12C\n" +
	"\bFilesGet\x12\x19.filesync.FilesGetRequest\x1a\x1a.filesync.FilesGetResponse0\x01\x128\n" +
	"\x05Check\x12\x16.filesync.CheckRequest\x1a\x17.filesync.CheckResponse\x12D\n" +
	"\tSpaceInfo\x12\x1a.filesync.SpaceInfoRequest\x1a\x1b.filesync.SpaceInfoResponse\x12J\n" +
	"\vAccountInfo\x12\x1c.filesync.AccountInfoRequest\x1a\x1d.filesync.AccountInfoResponse\x12A\n" +
	"\x0fAccountLimitSet\x12 .filesync.AccountLimitSetRequest\x1a\f.filesync.Ok\x12=\n" +
	"\rSpaceLimitSet\x12\x1e.filesync.SpaceLimitSetRequest\x1a\f.filesync.OkB\x16Z\x14commonfile/fileprotob\x06proto3"

var (
	file_commonfile_fileproto_protos_file_proto_rawDescOnce sync.Once
	file_commonfile_fileproto_protos_file_proto_rawDescData []byte
)

func file_commonfile_fileproto_protos_file_proto_rawDescGZIP() []byte {
	file_commonfile_fileproto_protos_file_proto_rawDescOnce.Do(func() {
		file_commonfile_fileproto_protos_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commonfile_fileproto_protos_file_proto_rawDesc), len(file_commonfile_fileproto_protos_file_proto_rawDesc)))
	})
	return file_commonfile_fileproto_protos_file_proto_rawDescData
}

var file_commonfile_fileproto_protos_file_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_commonfile_fileproto_protos_file_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_commonfile_fileproto_protos_file_proto_goTypes = []any{
	(ErrCodes)(0),                  // 0: filesync.ErrCodes
	(AvailabilityStatus)(0),        // 1: filesync.AvailabilityStatus
	(*Ok)(nil),                     // 2: filesync.Ok
	(*BlockGetRequest)(nil),        // 3: filesync.BlockGetRequest
	(*BlockGetResponse)(nil),       // 4: filesync.BlockGetResponse
	(*BlockPushRequest)(nil),       // 5: filesync.BlockPushRequest
	(*BlockPushManyRequest)(nil),   // 6: filesync.BlockPushManyRequest
	(*FileBlock)(nil),              // 7: filesync.FileBlock
	(*BlocksCheckRequest)(nil),     // 8: filesync.BlocksCheckRequest
	(*BlocksCheckResponse)(nil),    // 9: filesync.BlocksCheckResponse
	(*BlockAvailability)(nil),      // 10: filesync.BlockAvailability
	(*BlocksBindRequest)(nil),      // 11: filesync.BlocksBindRequest
	(*FilesDeleteRequest)(nil),     // 12: filesync.FilesDeleteRequest
	(*FilesDeleteResponse)(nil),    // 13: filesync.FilesDeleteResponse
	(*FilesInfoRequest)(nil),       // 14: filesync.FilesInfoRequest
	(*FilesInfoResponse)(nil),      // 15: filesync.FilesInfoResponse
	(*FileInfo)(nil),               // 16: filesync.FileInfo
	(*FilesGetRequest)(nil),        // 17: filesync.FilesGetRequest
	(*FilesGetResponse)(nil),       // 18: filesync.FilesGetResponse
	(*CheckRequest)(nil),           // 19: filesync.CheckRequest
	(*CheckResponse)(nil),          // 20: filesync.CheckResponse
	(*SpaceInfoRequest)(nil),       // 21: filesync.SpaceInfoRequest
	(*SpaceInfoResponse)(nil),      // 22: filesync.SpaceInfoResponse
	(*AccountInfoRequest)(nil),     // 23: filesync.AccountInfoRequest
	(*AccountInfoResponse)(nil),    // 24: filesync.AccountInfoResponse
	(*AccountLimitSetRequest)(nil), // 25: filesync.AccountLimitSetRequest
	(*SpaceLimitSetRequest)(nil),   // 26: filesync.SpaceLimitSetRequest
}
var file_commonfile_fileproto_protos_file_proto_depIdxs = []int32{
	7,  // 0: filesync.BlockPushManyRequest.fileBlocks:type_name -> filesync.FileBlock
	10, // 1: filesync.BlocksCheckResponse.blocksAvailability:type_name -> filesync.BlockAvailability
	1,  // 2: filesync.BlockAvailability.status:type_name -> filesync.AvailabilityStatus
	16, // 3: filesync.FilesInfoResponse.filesInfo:type_name -> filesync.FileInfo
	22, // 4: filesync.AccountInfoResponse.spaces:type_name -> filesync.SpaceInfoResponse
	3,  // 5: filesync.File.BlockGet:input_type -> filesync.BlockGetRequest
	5,  // 6: filesync.File.BlockPush:input_type -> filesync.BlockPushRequest
	6,  // 7: filesync.File.BlockPushMany:input_type -> filesync.BlockPushManyRequest
	8,  // 8: filesync.File.BlocksCheck:input_type -> filesync.BlocksCheckRequest
	11, // 9: filesync.File.BlocksBind:input_type -> filesync.BlocksBindRequest
	12, // 10: filesync.File.FilesDelete:input_type -> filesync.FilesDeleteRequest
	14, // 11: filesync.File.FilesInfo:input_type -> filesync.FilesInfoRequest
	17, // 12: filesync.File.FilesGet:input_type -> filesync.FilesGetRequest
	19, // 13: filesync.File.Check:input_type -> filesync.CheckRequest
	21, // 14: filesync.File.SpaceInfo:input_type -> filesync.SpaceInfoRequest
	23, // 15: filesync.File.AccountInfo:input_type -> filesync.AccountInfoRequest
	25, // 16: filesync.File.AccountLimitSet:input_type -> filesync.AccountLimitSetRequest
	26, // 17: filesync.File.SpaceLimitSet:input_type -> filesync.SpaceLimitSetRequest
	4,  // 18: filesync.File.BlockGet:output_type -> filesync.BlockGetResponse
	2,  // 19: filesync.File.BlockPush:output_type -> filesync.Ok
	2,  // 20: filesync.File.BlockPushMany:output_type -> filesync.Ok
	9,  // 21: filesync.File.BlocksCheck:output_type -> filesync.BlocksCheckResponse
	2,  // 22: filesync.File.BlocksBind:output_type -> filesync.Ok
	13, // 23: filesync.File.FilesDelete:output_type -> filesync.FilesDeleteResponse
	15, // 24: filesync.File.FilesInfo:output_type -> filesync.FilesInfoResponse
	18, // 25: filesync.File.FilesGet:output_type -> filesync.FilesGetResponse
	20, // 26: filesync.File.Check:output_type -> filesync.CheckResponse
	22, // 27: filesync.File.SpaceInfo:output_type -> filesync.SpaceInfoResponse
	24, // 28: filesync.File.AccountInfo:output_type -> filesync.AccountInfoResponse
	2,  // 29: filesync.File.AccountLimitSet:output_type -> filesync.Ok
	2,  // 30: filesync.File.SpaceLimitSet:output_type -> filesync.Ok
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_commonfile_fileproto_protos_file_proto_init() }
func file_commonfile_fileproto_protos_file_proto_init() {
	if File_commonfile_fileproto_protos_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonfile_fileproto_protos_file_proto_rawDesc), len(file_commonfile_fileproto_protos_file_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commonfile_fileproto_protos_file_proto_goTypes,
		DependencyIndexes: file_commonfile_fileproto_protos_file_proto_depIdxs,
		EnumInfos:         file_commonfile_fileproto_protos_file_proto_enumTypes,
		MessageInfos:      file_commonfile_fileproto_protos_file_proto_msgTypes,
	}.Build()
	File_commonfile_fileproto_protos_file_proto = out.File
	file_commonfile_fileproto_protos_file_proto_goTypes = nil
	file_commonfile_fileproto_protos_file_proto_depIdxs = nil
}
